import { SUBJECT_CATEGORIES, BOOKING_STATUS, BADGE_TYPES } from './constants';

// Mock User Data - Based on real TP programs
export const mockUsers = [
  {
    userId: 'user001',
    email: 'john.tan@student.tp.edu.sg',
    username: 'John Tan Wei Ming',
    studentId: '2301234A',
    major: 'Information Technology', // T30
    yearOfStudy: 2,
    avatar: 'https://ui-avatars.com/api/?name=John+Tan&background=6366f1&color=fff',
    role: ['student', 'tutor'],
    credits: 150,
    points: 280,
    badges: [BADGE_TYPES.NEWBIE, BADGE_TYPES.EXPERT],
    school: 'Temasek Polytechnic',
    createdAt: '2024-04-15T08:30:00Z',
    isActive: true
  },
  {
    userId: 'user002',
    email: 'sarah.lim@student.tp.edu.sg',
    username: 'Sarah Lim Hui Ting',
    studentId: '2301235B',
    major: 'Applied Artificial Intelligence', // T69
    yearOfStudy: 3,
    avatar: 'https://ui-avatars.com/api/?name=Sarah+Lim&background=10b981&color=fff',
    role: ['student', 'tutor'],
    credits: 200,
    points: 450,
    badges: [BADGE_TYPES.NEWBIE, BADGE_TYPES.EXPERT, BADGE_TYPES.VETERAN],
    school: 'Temasek Polytechnic',
    createdAt: '2024-03-20T10:00:00Z',
    isActive: true
  },
  {
    userId: 'user003',
    email: 'michael.wong@student.tp.edu.sg',
    username: 'Michael Wong Jun Hao',
    studentId: '2201236C',
    major: 'Cybersecurity & Digital Forensics', // T64
    yearOfStudy: 3,
    avatar: 'https://ui-avatars.com/api/?name=Michael+Wong&background=f59e0b&color=fff',
    role: ['student', 'tutor'],
    credits: 180,
    points: 380,
    badges: [BADGE_TYPES.NEWBIE, BADGE_TYPES.VETERAN, BADGE_TYPES.SCHOLAR],
    school: 'Temasek Polytechnic',
    createdAt: '2023-04-10T09:00:00Z',
    isActive: true
  },
  {
    userId: 'user004',
    email: 'emily.ng@student.tp.edu.sg',
    username: 'Emily Ng Xin Yi',
    studentId: '2301237D',
    major: 'Business Process & Systems Engineering', // T43
    yearOfStudy: 2,
    avatar: 'https://ui-avatars.com/api/?name=Emily+Ng&background=ec4899&color=fff',
    role: ['student', 'tutor'],
    credits: 160,
    points: 320,
    badges: [BADGE_TYPES.NEWBIE, BADGE_TYPES.EXPERT],
    school: 'Temasek Polytechnic',
    createdAt: '2024-04-01T10:00:00Z',
    isActive: true
  },
  {
    userId: 'user005',
    email: 'david.chen@student.tp.edu.sg',
    username: 'David Chen Kai Wen',
    studentId: '2301238E',
    major: 'Immersive Media & Game Development', // T65
    yearOfStudy: 2,
    avatar: 'https://ui-avatars.com/api/?name=David+Chen&background=8b5cf6&color=fff',
    role: ['student', 'tutor'],
    credits: 140,
    points: 250,
    badges: [BADGE_TYPES.NEWBIE],
    school: 'Temasek Polytechnic',
    createdAt: '2024-03-15T14:00:00Z',
    isActive: true
  },
  {
    userId: 'user006',
    email: 'rachel.teo@student.tp.edu.sg',
    username: 'Rachel Teo Mei Ling',
    studentId: '2201239F',
    major: 'Information Technology', // T30
    yearOfStudy: 3,
    avatar: 'https://ui-avatars.com/api/?name=Rachel+Teo&background=06b6d4&color=fff',
    role: ['student', 'tutor'],
    credits: 190,
    points: 410,
    badges: [BADGE_TYPES.NEWBIE, BADGE_TYPES.EXPERT, BADGE_TYPES.VETERAN],
    school: 'Temasek Polytechnic',
    createdAt: '2023-04-20T11:00:00Z',
    isActive: true
  },
  {
    userId: 'user007',
    email: 'james.lee@student.tp.edu.sg',
    username: 'James Lee Wei Jie',
    studentId: '2301240G',
    major: 'Big Data & Analytics', // T61
    yearOfStudy: 2,
    avatar: 'https://ui-avatars.com/api/?name=James+Lee&background=f97316&color=fff',
    role: ['student', 'tutor'],
    credits: 170,
    points: 290,
    badges: [BADGE_TYPES.NEWBIE, BADGE_TYPES.EXPERT],
    school: 'Temasek Polytechnic',
    createdAt: '2024-03-25T09:30:00Z',
    isActive: true
  },
  {
    userId: 'user008',
    email: 'amanda.koh@student.tp.edu.sg',
    username: 'Amanda Koh Si Min',
    studentId: '2301241H',
    major: 'Accountancy & Finance', // T02
    yearOfStudy: 2,
    avatar: 'https://ui-avatars.com/api/?name=Amanda+Koh&background=14b8a6&color=fff',
    role: ['student', 'tutor'],
    credits: 155,
    points: 260,
    badges: [BADGE_TYPES.NEWBIE],
    school: 'Temasek Polytechnic',
    createdAt: '2024-04-05T13:00:00Z',
    isActive: true
  }
];

// Mock Tutor Profile Data - Real TP courses and modules
export const mockTutorProfiles = [
  {
    profileId: 'profile001',
    userId: 'user001',
    bio: 'Year 2 Information Technology student passionate about software development and cloud technologies. Currently pursuing AWS Certified Cloud Practitioner certification. I have completed multiple full-stack projects and enjoy explaining programming concepts in simple, practical terms.',
    subjects: [
      { subjectId: 'sub001', subjectName: 'Programming Fundamentals', proficiencyLevel: 'expert', category: SUBJECT_CATEGORIES.PROGRAMMING },
      { subjectId: 'sub002', subjectName: 'Object-Oriented Programming', proficiencyLevel: 'advanced', category: SUBJECT_CATEGORIES.PROGRAMMING },
      { subjectId: 'sub003', subjectName: 'Database Design & Administration', proficiencyLevel: 'advanced', category: SUBJECT_CATEGORIES.PROGRAMMING },
      { subjectId: 'sub004', subjectName: 'Web Application Development', proficiencyLevel: 'expert', category: SUBJECT_CATEGORIES.PROGRAMMING }
    ],
    completedCourses: [
      { code: 'IT1001', name: 'Programming Fundamentals', grade: 'A' },
      { code: 'IT2001', name: 'Object-Oriented Programming', grade: 'A' },
      { code: 'IT2002', name: 'Database Design & Administration', grade: 'B+' },
      { code: 'IT2003', name: 'Data Structures & Algorithms', grade: 'A' }
    ],
    availableSlots: [
      { day: 'Monday', startTime: '14:00', endTime: '17:00', isRecurring: true },
      { day: 'Wednesday', startTime: '18:00', endTime: '21:00', isRecurring: true },
      { day: 'Friday', startTime: '15:00', endTime: '18:00', isRecurring: true }
    ],
    preferredLocation: ['Library @ TP', 'Online (Zoom/Teams)'],
    languages: ['English', 'Mandarin'],
    totalSessions: 45,
    totalHours: 68.5,
    averageRating: 4.9,
    totalReviews: 28,
    responseRate: 98,
    responseTime: 45,
    isVerified: true,
    status: 'active',
    school: 'Temasek Polytechnic'
  },
  {
    profileId: 'profile002',
    userId: 'user002',
    bio: 'Year 3 Applied AI student with strong foundation in Python, machine learning and data analytics. I have hands-on experience with TensorFlow, scikit-learn, and pandas. My teaching approach focuses on practical applications and real-world datasets to make AI concepts easier to understand.',
    subjects: [
      { subjectId: 'sub001', subjectName: 'Programming Fundamentals', proficiencyLevel: 'expert', category: SUBJECT_CATEGORIES.PROGRAMMING },
      { subjectId: 'sub005', subjectName: 'Python Programming', proficiencyLevel: 'expert', category: SUBJECT_CATEGORIES.PROGRAMMING },
      { subjectId: 'sub006', subjectName: 'Data Analytics', proficiencyLevel: 'expert', category: SUBJECT_CATEGORIES.PROGRAMMING },
      { subjectId: 'sub007', subjectName: 'Machine Learning Fundamentals', proficiencyLevel: 'advanced', category: SUBJECT_CATEGORIES.PROGRAMMING },
      { subjectId: 'sub008', subjectName: 'Mathematics for Computing', proficiencyLevel: 'advanced', category: SUBJECT_CATEGORIES.MATH }
    ],
    completedCourses: [
      { code: 'AI1001', name: 'Introduction to AI', grade: 'A' },
      { code: 'AI2001', name: 'Machine Learning', grade: 'A' },
      { code: 'AI2002', name: 'Data Analytics with Python', grade: 'A' },
      { code: 'AI2003', name: 'Neural Networks & Deep Learning', grade: 'A-' }
    ],
    availableSlots: [
      { day: 'Tuesday', startTime: '16:00', endTime: '19:00', isRecurring: true },
      { day: 'Thursday', startTime: '14:00', endTime: '17:00', isRecurring: true },
      { day: 'Saturday', startTime: '10:00', endTime: '14:00', isRecurring: true }
    ],
    preferredLocation: ['Online (Zoom/Teams)', 'Student Hub @ TP'],
    languages: ['English', 'Mandarin'],
    totalSessions: 52,
    totalHours: 78,
    averageRating: 4.8,
    totalReviews: 35,
    responseRate: 95,
    responseTime: 60,
    isVerified: true,
    status: 'active',
    school: 'Temasek Polytechnic'
  },
  {
    profileId: 'profile003',
    userId: 'user003',
    bio: 'Final year Cybersecurity & Digital Forensics student with industry internship experience. Proficient in network security, ethical hacking, and digital investigation techniques. I can share practical insights from real security assessments and help you understand complex security concepts through hands-on labs.',
    subjects: [
      { subjectId: 'sub002', subjectName: 'Object-Oriented Programming', proficiencyLevel: 'expert', category: SUBJECT_CATEGORIES.PROGRAMMING },
      { subjectId: 'sub009', subjectName: 'Network Fundamentals', proficiencyLevel: 'expert', category: SUBJECT_CATEGORIES.OTHER },
      { subjectId: 'sub010', subjectName: 'Cybersecurity Fundamentals', proficiencyLevel: 'expert', category: SUBJECT_CATEGORIES.OTHER },
      { subjectId: 'sub011', subjectName: 'Ethical Hacking', proficiencyLevel: 'advanced', category: SUBJECT_CATEGORIES.OTHER },
      { subjectId: 'sub012', subjectName: 'Linux Administration', proficiencyLevel: 'advanced', category: SUBJECT_CATEGORIES.OTHER }
    ],
    completedCourses: [
      { code: 'CDF1001', name: 'Introduction to Cybersecurity', grade: 'A' },
      { code: 'CDF2001', name: 'Network Security', grade: 'A' },
      { code: 'CDF2002', name: 'Ethical Hacking & Penetration Testing', grade: 'A' },
      { code: 'CDF3001', name: 'Digital Forensics', grade: 'A-' }
    ],
    availableSlots: [
      { day: 'Monday', startTime: '19:00', endTime: '21:00', isRecurring: true },
      { day: 'Wednesday', startTime: '14:00', endTime: '17:00', isRecurring: true },
      { day: 'Friday', startTime: '18:00', endTime: '21:00', isRecurring: true }
    ],
    preferredLocation: ['Library @ TP', 'Online (Zoom/Teams)'],
    languages: ['English', 'Mandarin'],
    totalSessions: 38,
    totalHours: 57,
    averageRating: 4.7,
    totalReviews: 24,
    responseRate: 92,
    responseTime: 90,
    isVerified: true,
    status: 'active',
    school: 'Temasek Polytechnic'
  },
  {
    profileId: 'profile004',
    userId: 'user004',
    bio: 'Year 2 Business Process & Systems Engineering student combining business analytics, mathematics and programming skills. I help students bridge the gap between technical concepts and business applications, making complex topics more relatable and practical.',
    subjects: [
      { subjectId: 'sub013', subjectName: 'Business Analytics', proficiencyLevel: 'expert', category: SUBJECT_CATEGORIES.OTHER },
      { subjectId: 'sub014', subjectName: 'Statistics & Probability', proficiencyLevel: 'advanced', category: SUBJECT_CATEGORIES.MATH },
      { subjectId: 'sub008', subjectName: 'Mathematics for Computing', proficiencyLevel: 'expert', category: SUBJECT_CATEGORIES.MATH },
      { subjectId: 'sub015', subjectName: 'Process Improvement Techniques', proficiencyLevel: 'advanced', category: SUBJECT_CATEGORIES.OTHER }
    ],
    completedCourses: [
      { code: 'BPS1001', name: 'Business Fundamentals', grade: 'A' },
      { code: 'BPS2001', name: 'Business Analytics', grade: 'A' },
      { code: 'BPS2002', name: 'Operations Research', grade: 'A' },
      { code: 'MAT1001', name: 'Mathematics for Business', grade: 'A-' }
    ],
    availableSlots: [
      { day: 'Tuesday', startTime: '10:00', endTime: '13:00', isRecurring: true },
      { day: 'Thursday', startTime: '15:00', endTime: '18:00', isRecurring: true }
    ],
    preferredLocation: ['Library @ TP', 'Study Pods @ TP'],
    languages: ['English'],
    totalSessions: 25,
    totalHours: 37.5,
    averageRating: 4.6,
    totalReviews: 18,
    responseRate: 94,
    responseTime: 75,
    isVerified: true,
    status: 'active',
    school: 'Temasek Polytechnic'
  },
  {
    profileId: 'profile005',
    userId: 'user005',
    bio: 'Year 2 Immersive Media & Game Development student with passion for interactive experiences. Proficient in Unity, C#, and 3D modeling. I can guide you through game development from concept to completion, with hands-on projects and portfolio building tips.',
    subjects: [
      { subjectId: 'sub016', subjectName: 'Game Programming', proficiencyLevel: 'expert', category: SUBJECT_CATEGORIES.PROGRAMMING },
      { subjectId: 'sub017', subjectName: 'Unity Game Engine', proficiencyLevel: 'advanced', category: SUBJECT_CATEGORIES.PROGRAMMING },
      { subjectId: 'sub018', subjectName: 'C# Programming', proficiencyLevel: 'advanced', category: SUBJECT_CATEGORIES.PROGRAMMING },
      { subjectId: 'sub019', subjectName: '3D Modeling & Animation', proficiencyLevel: 'intermediate', category: SUBJECT_CATEGORIES.OTHER }
    ],
    completedCourses: [
      { code: 'IMG1001', name: 'Introduction to Game Development', grade: 'A' },
      { code: 'IMG2001', name: 'Game Programming with Unity', grade: 'A-' },
      { code: 'IMG2002', name: '3D Graphics & Animation', grade: 'B+' }
    ],
    availableSlots: [
      { day: 'Monday', startTime: '18:00', endTime: '21:00', isRecurring: true },
      { day: 'Wednesday', startTime: '19:00', endTime: '22:00', isRecurring: true },
      { day: 'Saturday', startTime: '14:00', endTime: '18:00', isRecurring: true }
    ],
    preferredLocation: ['Online (Discord/Zoom)', 'Student Hub @ TP'],
    languages: ['English', 'Mandarin'],
    totalSessions: 30,
    totalHours: 45,
    averageRating: 4.5,
    totalReviews: 20,
    responseRate: 90,
    responseTime: 50,
    isVerified: true,
    status: 'active',
    school: 'Temasek Polytechnic'
  },
  {
    profileId: 'profile006',
    userId: 'user006',
    bio: 'Year 3 Information Technology student specializing in full-stack development and cloud computing. AWS Certified Cloud Practitioner with experience in React, Node.js, and AWS services. I focus on helping students build real-world projects and prepare for technical interviews.',
    subjects: [
      { subjectId: 'sub004', subjectName: 'Web Application Development', proficiencyLevel: 'expert', category: SUBJECT_CATEGORIES.PROGRAMMING },
      { subjectId: 'sub020', subjectName: 'Mobile Application Development', proficiencyLevel: 'advanced', category: SUBJECT_CATEGORIES.PROGRAMMING },
      { subjectId: 'sub003', subjectName: 'Database Design & Administration', proficiencyLevel: 'expert', category: SUBJECT_CATEGORIES.PROGRAMMING },
      { subjectId: 'sub021', subjectName: 'Cloud Computing with AWS', proficiencyLevel: 'advanced', category: SUBJECT_CATEGORIES.OTHER }
    ],
    completedCourses: [
      { code: 'IT2003', name: 'Data Structures & Algorithms', grade: 'A' },
      { code: 'IT3001', name: 'Advanced Web Development', grade: 'A' },
      { code: 'IT3002', name: 'Cloud Computing', grade: 'A-' }
    ],
    availableSlots: [
      { day: 'Tuesday', startTime: '17:00', endTime: '20:00', isRecurring: true },
      { day: 'Thursday', startTime: '16:00', endTime: '19:00', isRecurring: true },
      { day: 'Sunday', startTime: '10:00', endTime: '14:00', isRecurring: true }
    ],
    preferredLocation: ['Library @ TP', 'Online (Zoom/Teams)'],
    languages: ['English'],
    totalSessions: 42,
    totalHours: 63,
    averageRating: 4.8,
    totalReviews: 30,
    responseRate: 96,
    responseTime: 40,
    isVerified: true,
    status: 'active',
    school: 'Temasek Polytechnic'
  },
  {
    profileId: 'profile007',
    userId: 'user007',
    bio: 'Year 2 Big Data & Analytics student with expertise in data visualization, SQL, and Python analytics libraries. I enjoy making data analysis accessible and fun through real business case studies and interactive dashboards. Perfect for students looking to master Tableau, Power BI, or Excel.',
    subjects: [
      { subjectId: 'sub006', subjectName: 'Data Analytics', proficiencyLevel: 'expert', category: SUBJECT_CATEGORIES.PROGRAMMING },
      { subjectId: 'sub022', subjectName: 'SQL & Database Querying', proficiencyLevel: 'expert', category: SUBJECT_CATEGORIES.PROGRAMMING },
      { subjectId: 'sub023', subjectName: 'Data Visualization', proficiencyLevel: 'advanced', category: SUBJECT_CATEGORIES.OTHER },
      { subjectId: 'sub014', subjectName: 'Statistics & Probability', proficiencyLevel: 'advanced', category: SUBJECT_CATEGORIES.MATH },
      { subjectId: 'sub005', subjectName: 'Python Programming', proficiencyLevel: 'advanced', category: SUBJECT_CATEGORIES.PROGRAMMING }
    ],
    completedCourses: [
      { code: 'BDA1001', name: 'Introduction to Big Data', grade: 'A' },
      { code: 'BDA2001', name: 'Data Analytics with Python', grade: 'A' },
      { code: 'BDA2002', name: 'Data Visualization & Storytelling', grade: 'A-' }
    ],
    availableSlots: [
      { day: 'Monday', startTime: '15:00', endTime: '18:00', isRecurring: true },
      { day: 'Wednesday', startTime: '16:00', endTime: '19:00', isRecurring: true },
      { day: 'Friday', startTime: '14:00', endTime: '17:00', isRecurring: true }
    ],
    preferredLocation: ['Online (Zoom/Teams)', 'Library @ TP'],
    languages: ['English', 'Malay'],
    totalSessions: 28,
    totalHours: 42,
    averageRating: 4.7,
    totalReviews: 19,
    responseRate: 93,
    responseTime: 55,
    isVerified: true,
    status: 'active',
    school: 'Temasek Polytechnic'
  },
  {
    profileId: 'profile008',
    userId: 'user008',
    bio: 'Year 2 Accountancy & Finance student with strong analytical skills and passion for teaching financial concepts. I help students understand accounting principles, financial statements, and Excel for finance. My approach combines theory with practical applications using real company examples.',
    subjects: [
      { subjectId: 'sub024', subjectName: 'Financial Accounting', proficiencyLevel: 'expert', category: SUBJECT_CATEGORIES.OTHER },
      { subjectId: 'sub025', subjectName: 'Management Accounting', proficiencyLevel: 'advanced', category: SUBJECT_CATEGORIES.OTHER },
      { subjectId: 'sub026', subjectName: 'Excel for Finance', proficiencyLevel: 'expert', category: SUBJECT_CATEGORIES.OTHER },
      { subjectId: 'sub014', subjectName: 'Statistics & Probability', proficiencyLevel: 'intermediate', category: SUBJECT_CATEGORIES.MATH }
    ],
    completedCourses: [
      { code: 'ACC1001', name: 'Principles of Accounting', grade: 'A' },
      { code: 'ACC2001', name: 'Financial Accounting', grade: 'A' },
      { code: 'ACC2002', name: 'Cost & Management Accounting', grade: 'A-' }
    ],
    availableSlots: [
      { day: 'Tuesday', startTime: '14:00', endTime: '17:00', isRecurring: true },
      { day: 'Thursday', startTime: '18:00', endTime: '21:00', isRecurring: true },
      { day: 'Saturday', startTime: '09:00', endTime: '12:00', isRecurring: true }
    ],
    preferredLocation: ['Library @ TP', 'Online (Zoom/Teams)'],
    languages: ['English', 'Mandarin'],
    totalSessions: 22,
    totalHours: 33,
    averageRating: 4.6,
    totalReviews: 15,
    responseRate: 91,
    responseTime: 65,
    isVerified: true,
    status: 'active',
    school: 'Temasek Polytechnic'
  },
  {
    profileId: 'profileCurrent',
    userId: 'currentUser',
    bio: 'Year 2 Information Technology student with a passion for web development and programming. I enjoy helping fellow students understand coding concepts and building practical projects together. My teaching style focuses on hands-on learning and making complex topics simple and relatable.',
    subjects: [
      { subjectId: 'sub001', subjectName: 'Programming Fundamentals', proficiencyLevel: 'advanced', category: SUBJECT_CATEGORIES.PROGRAMMING },
      { subjectId: 'sub002', subjectName: 'Object-Oriented Programming', proficiencyLevel: 'advanced', category: SUBJECT_CATEGORIES.PROGRAMMING },
      { subjectId: 'sub004', subjectName: 'Web Application Development', proficiencyLevel: 'expert', category: SUBJECT_CATEGORIES.PROGRAMMING },
      { subjectId: 'sub003', subjectName: 'Database Design & Administration', proficiencyLevel: 'intermediate', category: SUBJECT_CATEGORIES.PROGRAMMING }
    ],
    completedCourses: [
      { code: 'IT1001', name: 'Programming Fundamentals', grade: 'A' },
      { code: 'IT2001', name: 'Object-Oriented Programming', grade: 'A-' },
      { code: 'IT2002', name: 'Database Design', grade: 'B+' }
    ],
    availableSlots: [
      { day: 'Monday', startTime: '16:00', endTime: '19:00', isRecurring: true },
      { day: 'Wednesday', startTime: '15:00', endTime: '18:00', isRecurring: true },
      { day: 'Friday', startTime: '17:00', endTime: '20:00', isRecurring: true }
    ],
    preferredLocation: ['Online (Zoom/Teams)', 'Library @ TP', 'Canteen'],
    languages: ['English', 'Mandarin'],
    totalSessions: 8,
    totalHours: 12,
    averageRating: 4.6,
    totalReviews: 5,
    responseRate: 95,
    responseTime: 25,
    isVerified: true,
    status: 'active',
    school: 'Temasek Polytechnic'
  }
];

// Mock Subject List - Based on real TP modules (moved here before mockTutors to avoid initialization error)
export const mockSubjects = [
  { subjectId: 'sub001', name: 'Programming Fundamentals', code: 'IT1001', category: SUBJECT_CATEGORIES.PROGRAMMING, icon: '', tutorCount: 15 },
  { subjectId: 'sub002', name: 'Object-Oriented Programming', code: 'IT2001', category: SUBJECT_CATEGORIES.PROGRAMMING, icon: '', tutorCount: 12 },
  { subjectId: 'sub003', name: 'Database Design & Administration', code: 'IT2002', category: SUBJECT_CATEGORIES.PROGRAMMING, icon: '', tutorCount: 10 },
  { subjectId: 'sub004', name: 'Web Application Development', code: 'IT3001', category: SUBJECT_CATEGORIES.PROGRAMMING, icon: '', tutorCount: 14 },
  { subjectId: 'sub005', name: 'Python Programming', code: 'AI1002', category: SUBJECT_CATEGORIES.PROGRAMMING, icon: '', tutorCount: 18 },
  { subjectId: 'sub006', name: 'Data Analytics', code: 'BDA2001', category: SUBJECT_CATEGORIES.PROGRAMMING, icon: '', tutorCount: 11 },
  { subjectId: 'sub007', name: 'Machine Learning Fundamentals', code: 'AI2001', category: SUBJECT_CATEGORIES.PROGRAMMING, icon: '', tutorCount: 8 },
  { subjectId: 'sub008', name: 'Mathematics for Computing', code: 'MAT1001', category: SUBJECT_CATEGORIES.MATH, icon: '', tutorCount: 9 },
  { subjectId: 'sub009', name: 'Network Fundamentals', code: 'CDF1002', category: SUBJECT_CATEGORIES.OTHER, icon: '', tutorCount: 7 },
  { subjectId: 'sub010', name: 'Cybersecurity Fundamentals', code: 'CDF1001', category: SUBJECT_CATEGORIES.OTHER, icon: '', tutorCount: 6 },
  { subjectId: 'sub011', name: 'Ethical Hacking', code: 'CDF2001', category: SUBJECT_CATEGORIES.OTHER, icon: '', tutorCount: 5 },
  { subjectId: 'sub012', name: 'Linux Administration', code: 'CDF2003', category: SUBJECT_CATEGORIES.OTHER, icon: '', tutorCount: 4 },
  { subjectId: 'sub013', name: 'Business Analytics', code: 'BPS2001', category: SUBJECT_CATEGORIES.OTHER, icon: '', tutorCount: 8 },
  { subjectId: 'sub014', name: 'Statistics & Probability', code: 'MAT2001', category: SUBJECT_CATEGORIES.MATH, icon: '', tutorCount: 10 },
  { subjectId: 'sub015', name: 'Process Improvement Techniques', code: 'BPS2002', category: SUBJECT_CATEGORIES.OTHER, icon: '', tutorCount: 5 },
  { subjectId: 'sub016', name: 'Game Programming', code: 'IMG2001', category: SUBJECT_CATEGORIES.PROGRAMMING, icon: '', tutorCount: 7 },
  { subjectId: 'sub017', name: 'Unity Game Engine', code: 'IMG2002', category: SUBJECT_CATEGORIES.PROGRAMMING, icon: '', tutorCount: 6 },
  { subjectId: 'sub018', name: 'C# Programming', code: 'IMG1002', category: SUBJECT_CATEGORIES.PROGRAMMING, icon: '', tutorCount: 8 },
  { subjectId: 'sub019', name: '3D Modeling & Animation', code: 'IMG2003', category: SUBJECT_CATEGORIES.OTHER, icon: '', tutorCount: 4 },
  { subjectId: 'sub020', name: 'Mobile Application Development', code: 'IT3002', category: SUBJECT_CATEGORIES.PROGRAMMING, icon: '', tutorCount: 9 },
  { subjectId: 'sub021', name: 'Cloud Computing with AWS', code: 'IT3003', category: SUBJECT_CATEGORIES.OTHER, icon: '', tutorCount: 7 },
  { subjectId: 'sub022', name: 'SQL & Database Querying', code: 'BDA1002', category: SUBJECT_CATEGORIES.PROGRAMMING, icon: '', tutorCount: 12 },
  { subjectId: 'sub023', name: 'Data Visualization', code: 'BDA2002', category: SUBJECT_CATEGORIES.OTHER, icon: '', tutorCount: 8 },
  { subjectId: 'sub024', name: 'Financial Accounting', code: 'ACC2001', category: SUBJECT_CATEGORIES.OTHER, icon: '', tutorCount: 10 },
  { subjectId: 'sub025', name: 'Management Accounting', code: 'ACC2002', category: SUBJECT_CATEGORIES.OTHER, icon: '', tutorCount: 7 },
  { subjectId: 'sub026', name: 'Excel for Finance', code: 'ACC1002', category: SUBJECT_CATEGORIES.OTHER, icon: '', tutorCount: 11 }
];

// Merge user and tutor profile data with proper field mapping
export const mockTutors = mockTutorProfiles.map(profile => {
  const user = mockUsers.find(u => u.userId === profile.userId) || {
    userId: profile.userId,
    username: 'Tutor',
    avatar: 'https://ui-avatars.com/api/?name=Tutor&background=6366f1&color=fff',
    school: 'Temasek Polytechnic'
  };

  // Map subjects to have both subjectName and code fields
  const subjects = profile.subjects.map(sub => {
    const matchedSubject = mockSubjects.find(ms => ms.name === sub.subjectName);
    return {
      ...sub,
      name: sub.subjectName,
      code: matchedSubject?.code || sub.subjectName
    };
  });

  // Keep availableSlots as objects for algorithm, but also add formatted strings for display
  const availableSlots = profile.availableSlots;
  const availableSlotsFormatted = profile.availableSlots.map(slot =>
    `${slot.day} ${slot.startTime}-${slot.endTime.substring(0, 5)}`
  );

  // Rename preferredLocation to preferredLocations (plural)
  const preferredLocations = profile.preferredLocation;

  // Merge hourlyRate from completedCourses count
  const hourlyRate = 10 + profile.completedCourses.length;

  return {
    ...user,
    ...profile,
    subjects,
    availableSlots, // Objects for algorithm
    availableSlotsDisplay: availableSlotsFormatted, // Strings for UI display
    preferredLocations,
    hourlyRate,
    // Keep profile fields that might be needed
    profileCompletion: 85,
    responseRate: profile.responseRate,
    responseTime: profile.responseTime
  };
});

// Mock Review Data
export const mockReviews = [
  {
    reviewId: 'review001',
    bookingId: 'booking001',
    tutorId: 'user001',
    studentId: 'student001',
    rating: 5,
    comment: 'John is an excellent tutor! He explained OOP concepts using real-world examples from his projects. His explanation of inheritance and polymorphism finally clicked for me. Highly recommend for IT students!',
    tags: ['Patient', 'Clear Explanation', 'Well Prepared'],
    isAnonymous: false,
    isVerified: true,
    helpfulCount: 12,
    studentName: 'Marcus Lim',
    studentAvatar: 'https://ui-avatars.com/api/?name=Marcus+Lim&background=random',
    createdAt: '2024-10-15T20:00:00Z'
  },
  {
    reviewId: 'review002',
    bookingId: 'booking002',
    tutorId: 'user001',
    studentId: 'student002',
    rating: 5,
    comment: 'Very punctual and came well-prepared with practice questions on database normalization. He made sure I understood each normal form before moving on. Thanks for helping me ace my IT2002 quiz!',
    tags: ['Punctual', 'Responsible', 'Patient'],
    isAnonymous: true,
    isVerified: true,
    helpfulCount: 8,
    studentName: 'Student from T30',
    studentAvatar: 'https://ui-avatars.com/api/?name=Student&background=random',
    createdAt: '2024-10-10T18:30:00Z'
  },
  {
    reviewId: 'review003',
    bookingId: 'booking003',
    tutorId: 'user002',
    studentId: 'student003',
    rating: 5,
    comment: 'Sarah\'s data analytics sessions are gold! She used a real Kaggle dataset to teach pandas and matplotlib. Learned more in 2 hours than weeks of self-study. Perfect for AI students struggling with data preprocessing.',
    tags: ['Professional', 'Efficient', 'Well Prepared'],
    isAnonymous: false,
    isVerified: true,
    helpfulCount: 15,
    studentName: 'Priya Kumar',
    studentAvatar: 'https://ui-avatars.com/api/?name=Priya+Kumar&background=random',
    createdAt: '2024-10-12T16:00:00Z'
  },
  {
    reviewId: 'review004',
    bookingId: 'booking004',
    tutorId: 'user002',
    studentId: 'student004',
    rating: 4,
    comment: 'Great at teaching ML fundamentals! Sometimes goes a bit fast when explaining linear algebra concepts, but overall very knowledgeable. Would book again for neural networks module.',
    tags: ['Professional', 'Friendly'],
    isAnonymous: true,
    isVerified: true,
    helpfulCount: 5,
    studentName: 'Student from T69',
    studentAvatar: 'https://ui-avatars.com/api/?name=Student&background=random',
    createdAt: '2024-10-08T19:00:00Z'
  },
  {
    reviewId: 'review005',
    bookingId: 'booking005',
    tutorId: 'user003',
    studentId: 'student005',
    rating: 5,
    comment: 'Michael\'s ethical hacking session was mind-blowing! He demonstrated actual penetration testing techniques and explained how to use Kali Linux tools. Perfect for CDF students preparing for practical assessments.',
    tags: ['Professional', 'Detailed', 'Efficient'],
    isAnonymous: false,
    isVerified: true,
    helpfulCount: 10,
    studentName: 'Arjun Singh',
    studentAvatar: 'https://ui-avatars.com/api/?name=Arjun+Singh&background=random',
    createdAt: '2024-10-18T21:00:00Z'
  },
  {
    reviewId: 'review006',
    bookingId: 'booking006',
    tutorId: 'user004',
    studentId: 'student006',
    rating: 5,
    comment: 'Emily made business analytics so much clearer! She connected the mathematical concepts to actual business decisions. Her process improvement examples from BPSE projects really helped me understand.',
    tags: ['Clear Explanation', 'Patient', 'Helpful'],
    isAnonymous: false,
    isVerified: true,
    helpfulCount: 9,
    studentName: 'Daniel Goh',
    studentAvatar: 'https://ui-avatars.com/api/?name=Daniel+Goh&background=random',
    createdAt: '2024-10-20T17:30:00Z'
  },
  {
    reviewId: 'review007',
    bookingId: 'booking007',
    tutorId: 'user005',
    studentId: 'student007',
    rating: 4,
    comment: 'David helped me debug my Unity game project! Super hands-on approach with actual coding together. Learned C# scripting techniques I couldn\'t find in tutorials. Great for IMG students.',
    tags: ['Practical', 'Friendly', 'Helpful'],
    isAnonymous: true,
    isVerified: true,
    helpfulCount: 7,
    studentName: 'Student from T65',
    studentAvatar: 'https://ui-avatars.com/api/?name=Student&background=random',
    createdAt: '2024-10-16T19:00:00Z'
  },
  {
    reviewId: 'review008',
    bookingId: 'booking008',
    tutorId: 'user006',
    studentId: 'student008',
    rating: 5,
    comment: 'Rachel is brilliant! She helped me understand React hooks and state management for my FYP. Also shared tips on AWS deployment which saved me hours. Definitely booking her again before my presentation.',
    tags: ['Expert', 'Clear Explanation', 'Motivating'],
    isAnonymous: false,
    isVerified: true,
    helpfulCount: 14,
    studentName: 'Wei Ting',
    studentAvatar: 'https://ui-avatars.com/api/?name=Wei+Ting&background=random',
    createdAt: '2024-10-22T20:00:00Z'
  },
  {
    reviewId: 'review009',
    bookingId: 'booking009',
    tutorId: 'user007',
    studentId: 'student009',
    rating: 5,
    comment: 'James taught me Power BI from scratch! Created a real dashboard with sales data during our session. His teaching style is perfect for visual learners. Best investment of my credits!',
    tags: ['Patient', 'Well Prepared', 'Efficient'],
    isAnonymous: false,
    isVerified: true,
    helpfulCount: 11,
    studentName: 'Nurul Izzah',
    studentAvatar: 'https://ui-avatars.com/api/?name=Nurul+Izzah&background=random',
    createdAt: '2024-10-19T16:45:00Z'
  },
  // Additional reviews for user001 (John Tan)
  {
    reviewId: 'review010',
    tutorId: 'user001',
    studentId: 'student010',
    rating: 5,
    comment: 'John helped me understand data structures for my algorithm assignment. His explanation of binary trees and hash tables was crystal clear. Really appreciate his patience!',
    tags: ['Patient', 'Clear Explanation', 'Helpful'],
    isAnonymous: false,
    isVerified: true,
    helpfulCount: 6,
    studentName: 'Alex Tan',
    studentAvatar: 'https://ui-avatars.com/api/?name=Alex+Tan&background=random',
    createdAt: '2024-09-28T15:30:00Z'
  },
  {
    reviewId: 'review011',
    tutorId: 'user001',
    studentId: 'student011',
    rating: 4,
    comment: 'Good session on Java programming. Helped me fix bugs in my FYP code. Would have been 5 stars if he had more time slots available.',
    tags: ['Professional', 'Helpful'],
    isAnonymous: true,
    isVerified: true,
    helpfulCount: 3,
    studentName: 'Student from T34',
    studentAvatar: 'https://ui-avatars.com/api/?name=Student&background=random',
    createdAt: '2024-09-15T18:00:00Z'
  },
  {
    reviewId: 'review012',
    tutorId: 'user001',
    studentId: 'student012',
    rating: 5,
    comment: 'Excellent tutor! John walked me through the entire software development lifecycle for my project. His industry experience really shows. Highly recommend for IT students!',
    tags: ['Expert', 'Well Prepared', 'Motivating'],
    isAnonymous: false,
    isVerified: true,
    helpfulCount: 9,
    studentName: 'Melissa Wong',
    studentAvatar: 'https://ui-avatars.com/api/?name=Melissa+Wong&background=random',
    createdAt: '2024-08-22T14:00:00Z'
  },
  // Additional reviews for user002 (Sarah Chen)
  {
    reviewId: 'review013',
    tutorId: 'user002',
    studentId: 'student013',
    rating: 5,
    comment: 'Sarah is amazing at Python! She helped me optimize my code and taught me best practices for writing clean, efficient code. Lifesaver before my coding exam!',
    tags: ['Professional', 'Patient', 'Clear Explanation'],
    isAnonymous: false,
    isVerified: true,
    helpfulCount: 12,
    studentName: 'Ryan Koh',
    studentAvatar: 'https://ui-avatars.com/api/?name=Ryan+Koh&background=random',
    createdAt: '2024-09-10T16:30:00Z'
  },
  {
    reviewId: 'review014',
    tutorId: 'user002',
    studentId: 'student014',
    rating: 5,
    comment: 'Best ML tutor ever! Sarah explained neural networks in a way that actually makes sense. Used real examples from her internship projects. Worth every credit!',
    tags: ['Expert', 'Detailed', 'Motivating'],
    isAnonymous: false,
    isVerified: true,
    helpfulCount: 18,
    studentName: 'Zhi Wei',
    studentAvatar: 'https://ui-avatars.com/api/?name=Zhi+Wei&background=random',
    createdAt: '2024-08-30T19:00:00Z'
  },
  {
    reviewId: 'review015',
    tutorId: 'user002',
    studentId: 'student015',
    rating: 4,
    comment: 'Very knowledgeable about data science. Sometimes uses technical jargon but overall great session. Helped me with my AI assignment.',
    tags: ['Professional', 'Efficient'],
    isAnonymous: true,
    isVerified: true,
    helpfulCount: 4,
    studentName: 'Student from T42',
    studentAvatar: 'https://ui-avatars.com/api/?name=Student&background=random',
    createdAt: '2024-07-18T17:00:00Z'
  },
  // Additional reviews for user003 (Michael Lee)
  {
    reviewId: 'review016',
    tutorId: 'user003',
    studentId: 'student016',
    rating: 5,
    comment: 'Michael is a cybersecurity genius! He taught me network security concepts and showed me how to use Wireshark. Perfect for CDF students!',
    tags: ['Expert', 'Practical', 'Detailed'],
    isAnonymous: false,
    isVerified: true,
    helpfulCount: 13,
    studentName: 'Benjamin Lim',
    studentAvatar: 'https://ui-avatars.com/api/?name=Benjamin+Lim&background=random',
    createdAt: '2024-09-25T20:00:00Z'
  },
  {
    reviewId: 'review017',
    tutorId: 'user003',
    studentId: 'student017',
    rating: 5,
    comment: 'Helped me understand cryptography for my security module. Michael knows his stuff and explains complex topics in simple terms. Highly recommended!',
    tags: ['Clear Explanation', 'Patient', 'Well Prepared'],
    isAnonymous: false,
    isVerified: true,
    helpfulCount: 8,
    studentName: 'Jasmine Ng',
    studentAvatar: 'https://ui-avatars.com/api/?name=Jasmine+Ng&background=random',
    createdAt: '2024-08-14T18:30:00Z'
  },
  {
    reviewId: 'review018',
    tutorId: 'user003',
    studentId: 'student018',
    rating: 4,
    comment: 'Good session on Linux system administration. Michael is very knowledgeable but session felt a bit rushed. Still learned a lot though!',
    tags: ['Professional', 'Helpful'],
    isAnonymous: true,
    isVerified: true,
    helpfulCount: 5,
    studentName: 'Student from T71',
    studentAvatar: 'https://ui-avatars.com/api/?name=Student&background=random',
    createdAt: '2024-07-22T16:00:00Z'
  },
  // Additional reviews for user004 (Emily Ng)
  {
    reviewId: 'review019',
    tutorId: 'user004',
    studentId: 'student019',
    rating: 5,
    comment: 'Emily made business intelligence so much easier to understand! Her Excel and SQL skills are top-notch. Great for BPSE students struggling with data analysis.',
    tags: ['Clear Explanation', 'Patient', 'Practical'],
    isAnonymous: false,
    isVerified: true,
    helpfulCount: 10,
    studentName: 'Kevin Tan',
    studentAvatar: 'https://ui-avatars.com/api/?name=Kevin+Tan&background=random',
    createdAt: '2024-09-12T15:00:00Z'
  },
  {
    reviewId: 'review020',
    tutorId: 'user004',
    studentId: 'student020',
    rating: 5,
    comment: 'Excellent tutor for business analytics! Emily helped me with my BDA project and taught me proper data visualization techniques. Highly recommend!',
    tags: ['Professional', 'Well Prepared', 'Motivating'],
    isAnonymous: false,
    isVerified: true,
    helpfulCount: 7,
    studentName: 'Sarah Lim',
    studentAvatar: 'https://ui-avatars.com/api/?name=Sarah+Lim&background=random',
    createdAt: '2024-08-05T17:30:00Z'
  },
  {
    reviewId: 'review021',
    tutorId: 'user004',
    studentId: 'student021',
    rating: 4,
    comment: 'Very helpful for my process improvement assignment. Emily knows BPSE content well. Session was good but could use more practical examples.',
    tags: ['Helpful', 'Friendly'],
    isAnonymous: true,
    isVerified: true,
    helpfulCount: 3,
    studentName: 'Student from T55',
    studentAvatar: 'https://ui-avatars.com/api/?name=Student&background=random',
    createdAt: '2024-07-08T14:00:00Z'
  },
  // Additional reviews for user005 (David Ong)
  {
    reviewId: 'review022',
    tutorId: 'user005',
    studentId: 'student022',
    rating: 5,
    comment: 'David is an amazing game dev tutor! Helped me fix collision detection in my Unity project. His knowledge of C# and Unity is impressive. Perfect for IMG students!',
    tags: ['Expert', 'Practical', 'Patient'],
    isAnonymous: false,
    isVerified: true,
    helpfulCount: 14,
    studentName: 'Marcus Loh',
    studentAvatar: 'https://ui-avatars.com/api/?name=Marcus+Loh&background=random',
    createdAt: '2024-09-20T19:00:00Z'
  },
  {
    reviewId: 'review023',
    tutorId: 'user005',
    studentId: 'student023',
    rating: 5,
    comment: 'Super helpful session on 3D modeling! David taught me Blender shortcuts and proper UV mapping. Made my FYP assets look so much better!',
    tags: ['Detailed', 'Well Prepared', 'Helpful'],
    isAnonymous: false,
    isVerified: true,
    helpfulCount: 9,
    studentName: 'Rachel Chua',
    studentAvatar: 'https://ui-avatars.com/api/?name=Rachel+Chua&background=random',
    createdAt: '2024-08-18T16:00:00Z'
  },
  {
    reviewId: 'review024',
    tutorId: 'user005',
    studentId: 'student024',
    rating: 4,
    comment: 'Good tutor for game programming. David helped me understand Unity physics. Sometimes goes into too much detail but overall very knowledgeable.',
    tags: ['Professional', 'Friendly'],
    isAnonymous: true,
    isVerified: true,
    helpfulCount: 6,
    studentName: 'Student from T62',
    studentAvatar: 'https://ui-avatars.com/api/?name=Student&background=random',
    createdAt: '2024-07-25T18:30:00Z'
  },
  // Additional reviews for user006 (Rachel Teo)
  {
    reviewId: 'review025',
    tutorId: 'user006',
    studentId: 'student025',
    rating: 5,
    comment: 'Rachel is brilliant at web development! She helped me build a full-stack app with React and Node.js. Her code reviews were super helpful. Absolute legend!',
    tags: ['Expert', 'Clear Explanation', 'Motivating'],
    isAnonymous: false,
    isVerified: true,
    helpfulCount: 16,
    studentName: 'Jonathan Ng',
    studentAvatar: 'https://ui-avatars.com/api/?name=Jonathan+Ng&background=random',
    createdAt: '2024-09-18T20:00:00Z'
  },
  {
    reviewId: 'review026',
    tutorId: 'user006',
    studentId: 'student026',
    rating: 5,
    comment: 'Best cloud computing tutor! Rachel taught me AWS deployment and helped me set up CI/CD pipeline. Saved my FYP presentation!',
    tags: ['Professional', 'Practical', 'Efficient'],
    isAnonymous: false,
    isVerified: true,
    helpfulCount: 11,
    studentName: 'Amanda Koh',
    studentAvatar: 'https://ui-avatars.com/api/?name=Amanda+Koh&background=random',
    createdAt: '2024-08-28T17:00:00Z'
  },
  {
    reviewId: 'review027',
    tutorId: 'user006',
    studentId: 'student027',
    rating: 5,
    comment: 'Rachel helped me debug my REST API. Super patient and explained HTTP methods clearly. Great for fullstack module students!',
    tags: ['Patient', 'Clear Explanation', 'Helpful'],
    isAnonymous: false,
    isVerified: true,
    helpfulCount: 8,
    studentName: 'Bryan Tan',
    studentAvatar: 'https://ui-avatars.com/api/?name=Bryan+Tan&background=random',
    createdAt: '2024-07-12T19:30:00Z'
  },
  // Additional reviews for user007 (James Lim)
  {
    reviewId: 'review028',
    tutorId: 'user007',
    studentId: 'student028',
    rating: 5,
    comment: 'James is a data visualization master! Taught me Tableau from basics to advanced dashboards. His business analytics insights are gold!',
    tags: ['Expert', 'Well Prepared', 'Patient'],
    isAnonymous: false,
    isVerified: true,
    helpfulCount: 13,
    studentName: 'Michelle Tan',
    studentAvatar: 'https://ui-avatars.com/api/?name=Michelle+Tan&background=random',
    createdAt: '2024-09-08T16:00:00Z'
  },
  {
    reviewId: 'review029',
    tutorId: 'user007',
    studentId: 'student029',
    rating: 4,
    comment: 'Good session on SQL queries. James knows his databases well. Helped me optimize my queries for the BDA assignment. Recommended!',
    tags: ['Professional', 'Helpful'],
    isAnonymous: true,
    isVerified: true,
    helpfulCount: 5,
    studentName: 'Student from T48',
    studentAvatar: 'https://ui-avatars.com/api/?name=Student&background=random',
    createdAt: '2024-08-16T15:30:00Z'
  },
  {
    reviewId: 'review030',
    tutorId: 'user007',
    studentId: 'student030',
    rating: 5,
    comment: 'Amazing tutor! James helped me understand data warehousing concepts. His real-world examples from internship made everything click. Will book again!',
    tags: ['Clear Explanation', 'Practical', 'Motivating'],
    isAnonymous: false,
    isVerified: true,
    helpfulCount: 10,
    studentName: 'Daniel Goh',
    studentAvatar: 'https://ui-avatars.com/api/?name=Daniel+Goh&background=random',
    createdAt: '2024-07-30T18:00:00Z'
  },
  // Additional reviews for user008 (Amanda Toh)
  {
    reviewId: 'review031',
    tutorId: 'user008',
    studentId: 'student031',
    rating: 5,
    comment: 'Amanda is fantastic! She helped me with mobile app development using Flutter. Her step-by-step approach made it so easy to understand. Highly recommend!',
    tags: ['Patient', 'Clear Explanation', 'Well Prepared'],
    isAnonymous: false,
    isVerified: true,
    helpfulCount: 12,
    studentName: 'Ethan Lim',
    studentAvatar: 'https://ui-avatars.com/api/?name=Ethan+Lim&background=random',
    createdAt: '2024-09-22T17:30:00Z'
  },
  {
    reviewId: 'review032',
    tutorId: 'user008',
    studentId: 'student032',
    rating: 5,
    comment: 'Best tutor for UI/UX design! Amanda taught me Figma and helped design my app interface. Her design principles knowledge is impressive!',
    tags: ['Expert', 'Practical', 'Motivating'],
    isAnonymous: false,
    isVerified: true,
    helpfulCount: 15,
    studentName: 'Chloe Ng',
    studentAvatar: 'https://ui-avatars.com/api/?name=Chloe+Ng&background=random',
    createdAt: '2024-08-20T19:00:00Z'
  },
  {
    reviewId: 'review033',
    tutorId: 'user008',
    studentId: 'student033',
    rating: 4,
    comment: 'Good session on React Native. Amanda explained navigation and state management well. Would be perfect with more hands-on coding time.',
    tags: ['Helpful', 'Friendly'],
    isAnonymous: true,
    isVerified: true,
    helpfulCount: 6,
    studentName: 'Student from T39',
    studentAvatar: 'https://ui-avatars.com/api/?name=Student&background=random',
    createdAt: '2024-07-15T16:00:00Z'
  },
  // More recent reviews across all tutors
  {
    reviewId: 'review034',
    tutorId: 'user001',
    studentId: 'student034',
    rating: 5,
    comment: 'John saved my grade! Last minute help before my OOP exam. He quickly identified my weak areas and drilled me on the important concepts. Thank you!',
    tags: ['Efficient', 'Helpful', 'Responsive'],
    isAnonymous: false,
    isVerified: true,
    helpfulCount: 7,
    studentName: 'Hui Min',
    studentAvatar: 'https://ui-avatars.com/api/?name=Hui+Min&background=random',
    createdAt: '2024-10-25T21:00:00Z'
  },
  {
    reviewId: 'review035',
    tutorId: 'user002',
    studentId: 'student035',
    rating: 5,
    comment: 'Sarah is the GOAT for AI module! She explained backpropagation in a way that finally made sense. Her patience is unmatched!',
    tags: ['Patient', 'Expert', 'Clear Explanation'],
    isAnonymous: false,
    isVerified: true,
    helpfulCount: 20,
    studentName: 'Kai Jun',
    studentAvatar: 'https://ui-avatars.com/api/?name=Kai+Jun&background=random',
    createdAt: '2024-10-23T18:00:00Z'
  },
  {
    reviewId: 'review036',
    tutorId: 'user003',
    studentId: 'student036',
    rating: 5,
    comment: 'Michael taught me reverse engineering! Super cool session on analyzing malware. Perfect prep for my CDF practical exam!',
    tags: ['Expert', 'Detailed', 'Practical'],
    isAnonymous: false,
    isVerified: true,
    helpfulCount: 9,
    studentName: 'Vishal Kumar',
    studentAvatar: 'https://ui-avatars.com/api/?name=Vishal+Kumar&background=random',
    createdAt: '2024-10-21T20:30:00Z'
  },
  {
    reviewId: 'review037',
    tutorId: 'user006',
    studentId: 'student037',
    rating: 5,
    comment: 'Rachel is amazing! She reviewed my entire FYP codebase and gave me tons of improvement suggestions. My project is 10x better now!',
    tags: ['Professional', 'Detailed', 'Motivating'],
    isAnonymous: false,
    isVerified: true,
    helpfulCount: 17,
    studentName: 'Jeremy Tan',
    studentAvatar: 'https://ui-avatars.com/api/?name=Jeremy+Tan&background=random',
    createdAt: '2024-10-24T19:00:00Z'
  },
  {
    reviewId: 'review038',
    tutorId: 'user008',
    studentId: 'student038',
    rating: 4,
    comment: 'Amanda helped me with my mobile app project. Good knowledge of cross-platform development. Session was helpful!',
    tags: ['Helpful', 'Professional'],
    isAnonymous: true,
    isVerified: true,
    helpfulCount: 4,
    studentName: 'Student from T51',
    studentAvatar: 'https://ui-avatars.com/api/?name=Student&background=random',
    createdAt: '2024-10-26T17:00:00Z'
  },
  {
    reviewId: 'review039',
    tutorId: 'currentUser',
    studentId: 'student039',
    rating: 5,
    comment: 'Alex is an amazing tutor! He helped me debug my web application project and explained React hooks in a way that finally made sense. Very patient and encouraging. Highly recommend for web dev help!',
    tags: ['Patient', 'Clear Explanation', 'Helpful'],
    isAnonymous: false,
    isVerified: true,
    helpfulCount: 8,
    studentName: 'Benjamin Koh',
    studentAvatar: 'https://ui-avatars.com/api/?name=Benjamin+Koh&background=random',
    createdAt: '2024-10-18T14:30:00Z'
  },
  {
    reviewId: 'review040',
    tutorId: 'currentUser',
    studentId: 'student040',
    rating: 4,
    comment: 'Good session on OOP concepts. Alex used practical coding examples to explain inheritance and polymorphism. Would have preferred more time on abstract classes but overall very helpful.',
    tags: ['Clear Explanation', 'Professional'],
    isAnonymous: true,
    isVerified: true,
    helpfulCount: 5,
    studentName: 'Student from T30',
    studentAvatar: 'https://ui-avatars.com/api/?name=Student&background=random',
    createdAt: '2024-10-12T16:45:00Z'
  },
  {
    reviewId: 'review041',
    tutorId: 'currentUser',
    studentId: 'student041',
    rating: 5,
    comment: 'Alex helped me understand JavaScript closures and async programming for my IT3001 project. His explanations were clear and he shared useful resources. Really appreciate his help!',
    tags: ['Patient', 'Well Prepared', 'Helpful'],
    isAnonymous: false,
    isVerified: true,
    helpfulCount: 7,
    studentName: 'Chloe Lim',
    studentAvatar: 'https://ui-avatars.com/api/?name=Chloe+Lim&background=random',
    createdAt: '2024-10-08T19:15:00Z'
  },
  {
    reviewId: 'review042',
    tutorId: 'currentUser',
    studentId: 'student042',
    rating: 5,
    comment: 'Excellent tutor for programming fundamentals! Alex broke down complex algorithms into simple steps and provided lots of practice questions. My coding skills improved significantly after just a few sessions.',
    tags: ['Clear Explanation', 'Patient', 'Encouraging'],
    isAnonymous: false,
    isVerified: true,
    helpfulCount: 10,
    studentName: 'Daniel Tan',
    studentAvatar: 'https://ui-avatars.com/api/?name=Daniel+Tan&background=random',
    createdAt: '2024-09-30T13:20:00Z'
  },
  {
    reviewId: 'review043',
    tutorId: 'currentUser',
    studentId: 'student043',
    rating: 4,
    comment: 'Alex is very knowledgeable about web development. He helped me set up my first full-stack project with Node.js and MySQL. Session was productive and I learned a lot!',
    tags: ['Helpful', 'Professional', 'Knowledgeable'],
    isAnonymous: true,
    isVerified: true,
    helpfulCount: 6,
    studentName: 'Student from T30',
    studentAvatar: 'https://ui-avatars.com/api/?name=Student&background=random',
    createdAt: '2024-09-22T15:00:00Z'
  },
  {
    reviewId: 'review044',
    tutorId: 'user001',
    studentId: 'currentUser',
    rating: 5,
    comment: 'John is an excellent tutor for OOP! He helped me understand polymorphism and inheritance for my IT2001 module. His real-world examples made everything click. Highly recommend!',
    tags: ['Clear Explanation', 'Patient', 'Well Prepared'],
    isAnonymous: false,
    isVerified: true,
    helpfulCount: 3,
    studentName: 'Alex Tan Kai Ming',
    studentAvatar: 'https://ui-avatars.com/api/?name=Alex+Tan&background=4f46e5&color=fff',
    createdAt: '2024-10-05T16:30:00Z'
  },
  {
    reviewId: 'review045',
    tutorId: 'user002',
    studentId: 'currentUser',
    rating: 5,
    comment: 'Sarah\'s data analytics session was amazing! She taught me pandas and data visualization using real datasets. I finally understand how to clean and analyze data properly. Thank you!',
    tags: ['Professional', 'Clear Explanation', 'Helpful'],
    isAnonymous: false,
    isVerified: true,
    helpfulCount: 4,
    studentName: 'Alex Tan Kai Ming',
    studentAvatar: 'https://ui-avatars.com/api/?name=Alex+Tan&background=4f46e5&color=fff',
    createdAt: '2024-09-18T14:00:00Z'
  },
  {
    reviewId: 'review046',
    tutorId: 'user006',
    studentId: 'currentUser',
    rating: 4,
    comment: 'Rachel helped me with database normalization concepts. Her explanations were clear and she provided good practice questions. Would recommend for database modules!',
    tags: ['Patient', 'Helpful'],
    isAnonymous: false,
    isVerified: true,
    helpfulCount: 2,
    studentName: 'Alex Tan Kai Ming',
    studentAvatar: 'https://ui-avatars.com/api/?name=Alex+Tan&background=4f46e5&color=fff',
    createdAt: '2024-08-25T11:30:00Z'
  }
];

// Mock Booking Data (Updated to 2025 for activity calendar)
export const mockBookings = [
  {
    bookingId: 'booking001',
    studentId: 'currentUser',
    tutorId: 'user001',
    subject: 'Object-Oriented Programming',
    date: '2025-10-30',
    timeSlot: '14:00 - 16:00',
    duration: 2,
    location: 'Online (Zoom)',
    notes: 'Need help understanding inheritance, polymorphism and abstract classes for IT2001 module. Have quiz next week.',
    status: 'confirmed',
    createdAt: '2025-10-20T10:00:00Z',
    hasReview: false
  },
  {
    bookingId: 'booking002',
    studentId: 'currentUser',
    tutorId: 'user002',
    subject: 'Machine Learning Fundamentals',
    date: '2025-10-28',
    timeSlot: '16:00 - 17:30',
    duration: 1.5,
    location: 'Online (Zoom)',
    notes: 'Preparing for AI module exam - need revision on supervised learning algorithms and model evaluation metrics.',
    status: 'pending',
    sessionType: 'online',
    createdAt: '2025-10-22T14:00:00Z',
    hasReview: false
  },
  {
    bookingId: 'booking003',
    studentId: 'currentUser',
    tutorId: 'user001',
    subject: 'Database Design & Administration',
    date: '2025-10-15',
    timeSlot: '15:00 - 17:00',
    duration: 2,
    location: 'Library @ TP Level 3',
    notes: 'Learning database normalization (1NF, 2NF, 3NF) and ER diagram design for IT2002 project.',
    status: 'completed',
    createdAt: '2025-10-10T09:00:00Z',
    completedAt: '2025-10-15T17:00:00Z',
    hasReview: true
  },
  {
    bookingId: 'booking004',
    studentId: 'currentUser',
    tutorId: 'user003',
    subject: 'Cybersecurity Fundamentals',
    date: '2025-11-05',
    timeSlot: '14:00 - 16:00',
    duration: 2,
    location: 'Library @ TP Level 3',
    notes: 'Need help with network security concepts and cryptography basics.',
    status: 'confirmed',
    createdAt: '2025-10-25T10:00:00Z',
    hasReview: false
  },
  {
    bookingId: 'booking005',
    studentId: 'currentUser',
    tutorId: 'user002',
    subject: 'Python Programming',
    date: '2025-10-20',
    timeSlot: '16:00 - 18:00',
    duration: 2,
    location: 'Online (Zoom)',
    notes: 'Learn Python data structures and file handling.',
    status: 'completed',
    createdAt: '2025-10-15T09:00:00Z',
    completedAt: '2025-10-20T18:00:00Z',
    sessionType: 'online',
    hasReview: false
  },
  {
    bookingId: 'booking006',
    studentId: 'currentUser',
    tutorId: 'user004',
    subject: 'Business Analytics',
    date: '2025-10-12',
    timeSlot: '10:00 - 12:00',
    duration: 2,
    location: 'Student Hub @ TP',
    notes: 'Help with statistics and data interpretation for business case study.',
    status: 'cancelled',
    createdAt: '2025-10-08T10:00:00Z',
    cancelledAt: '2025-10-11T14:00:00Z',
    hasReview: false
  },
  // Historical bookings for activity calendar (past 12 weeks)
  {
    bookingId: 'booking007',
    studentId: 'currentUser',
    tutorId: 'user001',
    subject: 'Web Application Development',
    date: '2025-10-08',
    timeSlot: '14:00 - 16:00',
    duration: 2,
    location: 'Library @ TP',
    notes: 'React hooks and state management',
    status: 'completed',
    createdAt: '2024-10-05T10:00:00Z',
    completedAt: '2024-10-08T16:00:00Z',
    hasReview: true
  },
  {
    bookingId: 'booking008',
    studentId: 'currentUser',
    tutorId: 'user002',
    subject: 'Python Programming',
    date: '2025-10-05',
    timeSlot: '10:00 - 12:00',
    duration: 2,
    location: 'Online (Zoom)',
    notes: 'NumPy and Pandas for data analysis',
    status: 'completed',
    createdAt: '2024-10-01T09:00:00Z',
    completedAt: '2024-10-05T12:00:00Z',
    hasReview: true
  },
  {
    bookingId: 'booking009',
    studentId: 'currentUser',
    tutorId: 'user006',
    subject: 'Database Design & Administration',
    date: '2025-09-28',
    timeSlot: '15:00 - 17:00',
    duration: 2,
    location: 'Library @ TP',
    notes: 'SQL joins and complex queries',
    status: 'completed',
    createdAt: '2024-09-25T10:00:00Z',
    completedAt: '2024-09-28T17:00:00Z',
    hasReview: true
  },
  {
    bookingId: 'booking010',
    studentId: 'currentUser',
    tutorId: 'user001',
    subject: 'Object-Oriented Programming',
    date: '2025-09-25',
    timeSlot: '14:00 - 16:00',
    duration: 2,
    location: 'Library @ TP',
    notes: 'Design patterns review',
    status: 'completed',
    createdAt: '2024-09-20T10:00:00Z',
    completedAt: '2024-09-25T16:00:00Z',
    hasReview: true
  },
  {
    bookingId: 'booking011',
    studentId: 'currentUser',
    tutorId: 'user002',
    subject: 'Machine Learning Fundamentals',
    date: '2025-09-22',
    timeSlot: '10:00 - 12:00',
    duration: 2,
    location: 'Online (Zoom)',
    notes: 'Neural networks basics',
    status: 'completed',
    createdAt: '2024-09-18T09:00:00Z',
    completedAt: '2024-09-22T12:00:00Z',
    hasReview: true
  },
  {
    bookingId: 'booking012',
    studentId: 'currentUser',
    tutorId: 'user006',
    subject: 'Web Application Development',
    date: '2025-09-18',
    timeSlot: '16:00 - 18:00',
    duration: 2,
    location: 'Online (Zoom)',
    notes: 'RESTful API development',
    status: 'completed',
    createdAt: '2024-09-15T10:00:00Z',
    completedAt: '2024-09-18T18:00:00Z',
    hasReview: true
  },
  {
    bookingId: 'booking013',
    studentId: 'currentUser',
    tutorId: 'user001',
    subject: 'Object-Oriented Programming',
    date: '2025-09-14',
    timeSlot: '14:00 - 16:00',
    duration: 2,
    location: 'Library @ TP',
    notes: 'Exception handling and debugging',
    status: 'completed',
    createdAt: '2024-09-10T10:00:00Z',
    completedAt: '2024-09-14T16:00:00Z',
    hasReview: true
  },
  {
    bookingId: 'booking014',
    studentId: 'currentUser',
    tutorId: 'user002',
    subject: 'Data Analytics',
    date: '2025-09-11',
    timeSlot: '10:00 - 12:00',
    duration: 2,
    location: 'Student Hub @ TP',
    notes: 'Data visualization with matplotlib',
    status: 'completed',
    createdAt: '2024-09-08T09:00:00Z',
    completedAt: '2024-09-11T12:00:00Z',
    hasReview: true
  },
  {
    bookingId: 'booking015',
    studentId: 'currentUser',
    tutorId: 'user006',
    subject: 'Cloud Computing with AWS',
    date: '2025-09-07',
    timeSlot: '15:00 - 17:00',
    duration: 2,
    location: 'Online (Zoom)',
    notes: 'EC2 and S3 fundamentals',
    status: 'completed',
    createdAt: '2024-09-05T10:00:00Z',
    completedAt: '2024-09-07T17:00:00Z',
    hasReview: false
  },
  {
    bookingId: 'booking016',
    studentId: 'currentUser',
    tutorId: 'user001',
    subject: 'Programming Fundamentals',
    date: '2025-09-04',
    timeSlot: '14:00 - 16:00',
    duration: 2,
    location: 'Library @ TP',
    notes: 'Code optimization techniques',
    status: 'completed',
    createdAt: '2024-09-01T10:00:00Z',
    completedAt: '2024-09-04T16:00:00Z',
    hasReview: true
  },
  {
    bookingId: 'booking017',
    studentId: 'currentUser',
    tutorId: 'user002',
    subject: 'Python Programming',
    date: '2025-08-31',
    timeSlot: '10:00 - 12:00',
    duration: 2,
    location: 'Online (Zoom)',
    notes: 'Object-oriented Python',
    status: 'completed',
    createdAt: '2024-08-28T09:00:00Z',
    completedAt: '2024-08-31T12:00:00Z',
    hasReview: true
  },
  {
    bookingId: 'booking018',
    studentId: 'currentUser',
    tutorId: 'user006',
    subject: 'Database Design & Administration',
    date: '2025-08-28',
    timeSlot: '15:00 - 17:00',
    duration: 2,
    location: 'Library @ TP',
    notes: 'Transaction management and ACID properties',
    status: 'completed',
    createdAt: '2024-08-25T10:00:00Z',
    completedAt: '2024-08-28T17:00:00Z',
    hasReview: true
  },
  {
    bookingId: 'booking019',
    studentId: 'currentUser',
    tutorId: 'user001',
    subject: 'Web Application Development',
    date: '2025-08-24',
    timeSlot: '14:00 - 16:00',
    duration: 2,
    location: 'Student Hub @ TP',
    notes: 'Frontend frameworks comparison',
    status: 'completed',
    createdAt: '2024-08-20T10:00:00Z',
    completedAt: '2024-08-24T16:00:00Z',
    hasReview: true
  },
  {
    bookingId: 'booking020',
    studentId: 'currentUser',
    tutorId: 'user002',
    subject: 'Machine Learning Fundamentals',
    date: '2025-08-21',
    timeSlot: '10:00 - 12:00',
    duration: 2,
    location: 'Online (Zoom)',
    notes: 'Decision trees and random forests',
    status: 'completed',
    createdAt: '2024-08-18T09:00:00Z',
    completedAt: '2024-08-21T12:00:00Z',
    hasReview: true
  },
  // More historical data for richer activity calendar
  {
    bookingId: 'booking021',
    studentId: 'currentUser',
    tutorId: 'user001',
    subject: 'Object-Oriented Programming',
    date: '2025-08-17',
    timeSlot: '14:00 - 16:00',
    duration: 2,
    location: 'Library @ TP',
    notes: 'Review for midterm exam',
    status: 'completed',
    createdAt: '2024-08-14T10:00:00Z',
    completedAt: '2024-08-17T16:00:00Z',
    hasReview: true
  },
  {
    bookingId: 'booking022',
    studentId: 'currentUser',
    tutorId: 'user006',
    subject: 'Web Application Development',
    date: '2025-08-14',
    timeSlot: '16:00 - 18:00',
    duration: 2,
    location: 'Online (Zoom)',
    notes: 'JavaScript async programming',
    status: 'completed',
    createdAt: '2024-08-11T10:00:00Z',
    completedAt: '2024-08-14T18:00:00Z',
    hasReview: true
  },
  {
    bookingId: 'booking023',
    studentId: 'currentUser',
    tutorId: 'user002',
    subject: 'Python Programming',
    date: '2025-08-10',
    timeSlot: '10:00 - 12:00',
    duration: 2,
    location: 'Student Hub @ TP',
    notes: 'Advanced Python decorators',
    status: 'completed',
    createdAt: '2024-08-07T09:00:00Z',
    completedAt: '2024-08-10T12:00:00Z',
    hasReview: true
  },
  {
    bookingId: 'booking024',
    studentId: 'currentUser',
    tutorId: 'user001',
    subject: 'Database Design & Administration',
    date: '2025-08-07',
    timeSlot: '14:00 - 16:00',
    duration: 2,
    location: 'Library @ TP',
    notes: 'Database indexing and optimization',
    status: 'completed',
    createdAt: '2024-08-04T10:00:00Z',
    completedAt: '2024-08-07T16:00:00Z',
    hasReview: true
  },
  {
    bookingId: 'booking025',
    studentId: 'currentUser',
    tutorId: 'user006',
    subject: 'Cloud Computing with AWS',
    date: '2025-08-03',
    timeSlot: '15:00 - 17:00',
    duration: 2,
    location: 'Online (Zoom)',
    notes: 'Lambda functions and serverless',
    status: 'completed',
    createdAt: '2024-07-31T10:00:00Z',
    completedAt: '2024-08-03T17:00:00Z',
    hasReview: false
  },
  {
    bookingId: 'booking026',
    studentId: 'currentUser',
    tutorId: 'user002',
    subject: 'Data Analytics',
    date: '2025-10-26',
    timeSlot: '10:00 - 12:00',
    duration: 2,
    location: 'Online (Zoom)',
    notes: 'Statistical analysis with Python',
    status: 'completed',
    createdAt: '2024-10-23T09:00:00Z',
    completedAt: '2024-10-26T12:00:00Z',
    hasReview: true
  },
  {
    bookingId: 'booking027',
    studentId: 'currentUser',
    tutorId: 'user001',
    subject: 'Web Application Development',
    date: '2025-10-24',
    timeSlot: '14:00 - 16:00',
    duration: 2,
    location: 'Library @ TP',
    notes: 'React Router and navigation',
    status: 'completed',
    createdAt: '2024-10-21T10:00:00Z',
    completedAt: '2024-10-24T16:00:00Z',
    hasReview: true
  },
  {
    bookingId: 'booking028',
    studentId: 'currentUser',
    tutorId: 'user006',
    subject: 'Database Design & Administration',
    date: '2025-10-22',
    timeSlot: '15:00 - 17:00',
    duration: 2,
    location: 'Library @ TP',
    notes: 'Stored procedures and triggers',
    status: 'completed',
    createdAt: '2024-10-19T10:00:00Z',
    completedAt: '2024-10-22T17:00:00Z',
    hasReview: true
  },
  {
    bookingId: 'booking029',
    studentId: 'currentUser',
    tutorId: 'user002',
    subject: 'Machine Learning Fundamentals',
    date: '2025-10-19',
    timeSlot: '10:00 - 12:00',
    duration: 2,
    location: 'Online (Zoom)',
    notes: 'K-means clustering',
    status: 'completed',
    createdAt: '2024-10-16T09:00:00Z',
    completedAt: '2024-10-19T12:00:00Z',
    hasReview: true
  },
  {
    bookingId: 'booking030',
    studentId: 'currentUser',
    tutorId: 'user001',
    subject: 'Object-Oriented Programming',
    date: '2025-10-17',
    timeSlot: '14:00 - 16:00',
    duration: 2,
    location: 'Student Hub @ TP',
    notes: 'SOLID principles deep dive',
    status: 'completed',
    createdAt: '2024-10-14T10:00:00Z',
    completedAt: '2024-10-17T16:00:00Z',
    hasReview: true
  },
  {
    bookingId: 'booking031',
    studentId: 'currentUser',
    tutorId: 'user006',
    subject: 'Web Application Development',
    date: '2025-10-14',
    timeSlot: '16:00 - 18:00',
    duration: 2,
    location: 'Online (Zoom)',
    notes: 'State management with Redux',
    status: 'completed',
    createdAt: '2024-10-11T10:00:00Z',
    completedAt: '2024-10-14T18:00:00Z',
    hasReview: true
  },
  {
    bookingId: 'booking032',
    studentId: 'currentUser',
    tutorId: 'user002',
    subject: 'Python Programming',
    date: '2025-10-11',
    timeSlot: '10:00 - 12:00',
    duration: 2,
    location: 'Library @ TP',
    notes: 'Web scraping with BeautifulSoup',
    status: 'completed',
    createdAt: '2024-10-08T09:00:00Z',
    completedAt: '2024-10-11T12:00:00Z',
    hasReview: true
  },
  {
    bookingId: 'booking033',
    studentId: 'currentUser',
    tutorId: 'user001',
    subject: 'Programming Fundamentals',
    date: '2025-10-09',
    timeSlot: '14:00 - 16:00',
    duration: 2,
    location: 'Library @ TP',
    notes: 'Algorithm complexity analysis',
    status: 'completed',
    createdAt: '2024-10-06T10:00:00Z',
    completedAt: '2024-10-09T16:00:00Z',
    hasReview: true
  },
  {
    bookingId: 'booking034',
    studentId: 'currentUser',
    tutorId: 'user006',
    subject: 'Database Design & Administration',
    date: '2025-10-03',
    timeSlot: '15:00 - 17:00',
    duration: 2,
    location: 'Library @ TP',
    notes: 'Advanced SQL queries and subqueries',
    status: 'completed',
    createdAt: '2024-09-30T10:00:00Z',
    completedAt: '2024-10-03T17:00:00Z',
    hasReview: true
  },
  {
    bookingId: 'booking035',
    studentId: 'currentUser',
    tutorId: 'user002',
    subject: 'Data Analytics',
    date: '2025-10-01',
    timeSlot: '10:00 - 12:00',
    duration: 2,
    location: 'Online (Zoom)',
    notes: 'Exploratory data analysis techniques',
    status: 'completed',
    createdAt: '2024-09-28T09:00:00Z',
    completedAt: '2024-10-01T12:00:00Z',
    hasReview: true
  },
  {
    bookingId: 'booking036',
    studentId: 'currentUser',
    tutorId: 'user001',
    subject: 'Object-Oriented Programming',
    date: '2025-09-30',
    timeSlot: '14:00 - 16:00',
    duration: 2,
    location: 'Student Hub @ TP',
    notes: 'Factory and Builder patterns',
    status: 'completed',
    createdAt: '2024-09-27T10:00:00Z',
    completedAt: '2024-09-30T16:00:00Z',
    hasReview: true
  },
  {
    bookingId: 'booking037',
    studentId: 'currentUser',
    tutorId: 'user006',
    subject: 'Cloud Computing with AWS',
    date: '2025-09-27',
    timeSlot: '15:00 - 17:00',
    duration: 2,
    location: 'Online (Zoom)',
    notes: 'RDS and database services',
    status: 'completed',
    createdAt: '2024-09-24T10:00:00Z',
    completedAt: '2024-09-27T17:00:00Z',
    hasReview: false
  },
  {
    bookingId: 'booking038',
    studentId: 'currentUser',
    tutorId: 'user002',
    subject: 'Machine Learning Fundamentals',
    date: '2025-09-24',
    timeSlot: '10:00 - 12:00',
    duration: 2,
    location: 'Library @ TP',
    notes: 'Support Vector Machines',
    status: 'completed',
    createdAt: '2024-09-21T09:00:00Z',
    completedAt: '2024-09-24T12:00:00Z',
    hasReview: true
  },
  {
    bookingId: 'booking039',
    studentId: 'currentUser',
    tutorId: 'user001',
    subject: 'Web Application Development',
    date: '2025-09-21',
    timeSlot: '14:00 - 16:00',
    duration: 2,
    location: 'Library @ TP',
    notes: 'API authentication and JWT',
    status: 'completed',
    createdAt: '2024-09-18T10:00:00Z',
    completedAt: '2024-09-21T16:00:00Z',
    hasReview: true
  },
  {
    bookingId: 'booking040',
    studentId: 'currentUser',
    tutorId: 'user006',
    subject: 'Database Design & Administration',
    date: '2025-09-19',
    timeSlot: '15:00 - 17:00',
    duration: 2,
    location: 'Student Hub @ TP',
    notes: 'Database backup and recovery',
    status: 'completed',
    createdAt: '2025-09-16T10:00:00Z',
    completedAt: '2025-09-19T17:00:00Z',
    hasReview: true
  },
  // Additional data for 24-week activity calendar (May - September 2025)
  {
    bookingId: 'booking041',
    studentId: 'currentUser',
    tutorId: 'user001',
    subject: 'Object-Oriented Programming',
    date: '2025-09-16',
    timeSlot: '14:00 - 16:00',
    duration: 2,
    location: 'Library @ TP',
    notes: 'Singleton and Factory patterns',
    status: 'completed',
    createdAt: '2025-09-13T10:00:00Z',
    completedAt: '2025-09-16T16:00:00Z',
    hasReview: true
  },
  {
    bookingId: 'booking042',
    studentId: 'currentUser',
    tutorId: 'user002',
    subject: 'Machine Learning Fundamentals',
    date: '2025-09-13',
    timeSlot: '10:00 - 12:00',
    duration: 2,
    location: 'Online (Zoom)',
    notes: 'Ensemble methods and boosting',
    status: 'completed',
    createdAt: '2025-09-10T09:00:00Z',
    completedAt: '2025-09-13T12:00:00Z',
    hasReview: true
  },
  {
    bookingId: 'booking043',
    studentId: 'currentUser',
    tutorId: 'user006',
    subject: 'Web Application Development',
    date: '2025-09-10',
    timeSlot: '16:00 - 18:00',
    duration: 2,
    location: 'Library @ TP',
    notes: 'WebSocket and real-time features',
    status: 'completed',
    createdAt: '2025-09-07T10:00:00Z',
    completedAt: '2025-09-10T18:00:00Z',
    hasReview: true
  },
  {
    bookingId: 'booking044',
    studentId: 'currentUser',
    tutorId: 'user001',
    subject: 'Programming Fundamentals',
    date: '2025-09-06',
    timeSlot: '14:00 - 16:00',
    duration: 2,
    location: 'Student Hub @ TP',
    notes: 'Recursion and dynamic programming',
    status: 'completed',
    createdAt: '2025-09-03T10:00:00Z',
    completedAt: '2025-09-06T16:00:00Z',
    hasReview: true
  },
  {
    bookingId: 'booking045',
    studentId: 'currentUser',
    tutorId: 'user002',
    subject: 'Data Analytics',
    date: '2025-09-03',
    timeSlot: '10:00 - 12:00',
    duration: 2,
    location: 'Online (Zoom)',
    notes: 'Time series analysis',
    status: 'completed',
    createdAt: '2025-08-31T09:00:00Z',
    completedAt: '2025-09-03T12:00:00Z',
    hasReview: true
  },
  {
    bookingId: 'booking046',
    studentId: 'currentUser',
    tutorId: 'user006',
    subject: 'Database Design & Administration',
    date: '2025-08-30',
    timeSlot: '15:00 - 17:00',
    duration: 2,
    location: 'Library @ TP',
    notes: 'Query optimization techniques',
    status: 'completed',
    createdAt: '2025-08-27T10:00:00Z',
    completedAt: '2025-08-30T17:00:00Z',
    hasReview: true
  },
  {
    bookingId: 'booking047',
    studentId: 'currentUser',
    tutorId: 'user001',
    subject: 'Object-Oriented Programming',
    date: '2025-08-27',
    timeSlot: '14:00 - 16:00',
    duration: 2,
    location: 'Library @ TP',
    notes: 'Dependency injection and IoC',
    status: 'completed',
    createdAt: '2025-08-24T10:00:00Z',
    completedAt: '2025-08-27T16:00:00Z',
    hasReview: true
  },
  {
    bookingId: 'booking048',
    studentId: 'currentUser',
    tutorId: 'user002',
    subject: 'Python Programming',
    date: '2025-08-23',
    timeSlot: '10:00 - 12:00',
    duration: 2,
    location: 'Online (Zoom)',
    notes: 'Multithreading and multiprocessing',
    status: 'completed',
    createdAt: '2025-08-20T09:00:00Z',
    completedAt: '2025-08-23T12:00:00Z',
    hasReview: true
  },
  {
    bookingId: 'booking049',
    studentId: 'currentUser',
    tutorId: 'user006',
    subject: 'Cloud Computing with AWS',
    date: '2025-08-20',
    timeSlot: '15:00 - 17:00',
    duration: 2,
    location: 'Online (Zoom)',
    notes: 'DynamoDB and NoSQL databases',
    status: 'completed',
    createdAt: '2025-08-17T10:00:00Z',
    completedAt: '2025-08-20T17:00:00Z',
    hasReview: false
  },
  {
    bookingId: 'booking050',
    studentId: 'currentUser',
    tutorId: 'user001',
    subject: 'Web Application Development',
    date: '2025-08-16',
    timeSlot: '14:00 - 16:00',
    duration: 2,
    location: 'Library @ TP',
    notes: 'Progressive Web Apps (PWA)',
    status: 'completed',
    createdAt: '2025-08-13T10:00:00Z',
    completedAt: '2025-08-16T16:00:00Z',
    hasReview: true
  },
  {
    bookingId: 'booking051',
    studentId: 'currentUser',
    tutorId: 'user002',
    subject: 'Machine Learning Fundamentals',
    date: '2025-08-13',
    timeSlot: '10:00 - 12:00',
    duration: 2,
    location: 'Student Hub @ TP',
    notes: 'Natural language processing basics',
    status: 'completed',
    createdAt: '2025-08-10T09:00:00Z',
    completedAt: '2025-08-13T12:00:00Z',
    hasReview: true
  },
  {
    bookingId: 'booking052',
    studentId: 'currentUser',
    tutorId: 'user006',
    subject: 'Database Design & Administration',
    date: '2025-08-09',
    timeSlot: '15:00 - 17:00',
    duration: 2,
    location: 'Library @ TP',
    notes: 'Replication and sharding',
    status: 'completed',
    createdAt: '2025-08-06T10:00:00Z',
    completedAt: '2025-08-09T17:00:00Z',
    hasReview: true
  },
  {
    bookingId: 'booking053',
    studentId: 'currentUser',
    tutorId: 'user001',
    subject: 'Programming Fundamentals',
    date: '2025-08-06',
    timeSlot: '14:00 - 16:00',
    duration: 2,
    location: 'Student Hub @ TP',
    notes: 'Graph algorithms and BFS/DFS',
    status: 'completed',
    createdAt: '2025-08-03T10:00:00Z',
    completedAt: '2025-08-06T16:00:00Z',
    hasReview: true
  },
  {
    bookingId: 'booking054',
    studentId: 'currentUser',
    tutorId: 'user002',
    subject: 'Data Analytics',
    date: '2025-08-02',
    timeSlot: '10:00 - 12:00',
    duration: 2,
    location: 'Online (Zoom)',
    notes: 'A/B testing and experimentation',
    status: 'completed',
    createdAt: '2025-07-30T09:00:00Z',
    completedAt: '2025-08-02T12:00:00Z',
    hasReview: true
  },
  {
    bookingId: 'booking055',
    studentId: 'currentUser',
    tutorId: 'user006',
    subject: 'Web Application Development',
    date: '2025-07-30',
    timeSlot: '16:00 - 18:00',
    duration: 2,
    location: 'Library @ TP',
    notes: 'GraphQL API development',
    status: 'completed',
    createdAt: '2025-07-27T10:00:00Z',
    completedAt: '2025-07-30T18:00:00Z',
    hasReview: true
  },
  {
    bookingId: 'booking056',
    studentId: 'currentUser',
    tutorId: 'user001',
    subject: 'Object-Oriented Programming',
    date: '2025-07-26',
    timeSlot: '14:00 - 16:00',
    duration: 2,
    location: 'Library @ TP',
    notes: 'Command and Observer patterns',
    status: 'completed',
    createdAt: '2025-07-23T10:00:00Z',
    completedAt: '2025-07-26T16:00:00Z',
    hasReview: true
  },
  {
    bookingId: 'booking057',
    studentId: 'currentUser',
    tutorId: 'user002',
    subject: 'Python Programming',
    date: '2025-07-23',
    timeSlot: '10:00 - 12:00',
    duration: 2,
    location: 'Online (Zoom)',
    notes: 'Context managers and generators',
    status: 'completed',
    createdAt: '2025-07-20T09:00:00Z',
    completedAt: '2025-07-23T12:00:00Z',
    hasReview: true
  },
  {
    bookingId: 'booking058',
    studentId: 'currentUser',
    tutorId: 'user006',
    subject: 'Cloud Computing with AWS',
    date: '2025-07-19',
    timeSlot: '15:00 - 17:00',
    duration: 2,
    location: 'Online (Zoom)',
    notes: 'API Gateway and microservices',
    status: 'completed',
    createdAt: '2025-07-16T10:00:00Z',
    completedAt: '2025-07-19T17:00:00Z',
    hasReview: false
  },
  {
    bookingId: 'booking059',
    studentId: 'currentUser',
    tutorId: 'user001',
    subject: 'Database Design & Administration',
    date: '2025-07-16',
    timeSlot: '14:00 - 16:00',
    duration: 2,
    location: 'Library @ TP',
    notes: 'Performance tuning and profiling',
    status: 'completed',
    createdAt: '2025-07-13T10:00:00Z',
    completedAt: '2025-07-16T16:00:00Z',
    hasReview: true
  },
  {
    bookingId: 'booking060',
    studentId: 'currentUser',
    tutorId: 'user002',
    subject: 'Machine Learning Fundamentals',
    date: '2025-07-12',
    timeSlot: '10:00 - 12:00',
    duration: 2,
    location: 'Student Hub @ TP',
    notes: 'Feature engineering techniques',
    status: 'completed',
    createdAt: '2025-07-09T09:00:00Z',
    completedAt: '2025-07-12T12:00:00Z',
    hasReview: true
  },
  {
    bookingId: 'booking061',
    studentId: 'currentUser',
    tutorId: 'user006',
    subject: 'Web Application Development',
    date: '2025-07-09',
    timeSlot: '16:00 - 18:00',
    duration: 2,
    location: 'Library @ TP',
    notes: 'Testing with Jest and React Testing Library',
    status: 'completed',
    createdAt: '2025-07-06T10:00:00Z',
    completedAt: '2025-07-09T18:00:00Z',
    hasReview: true
  },
  {
    bookingId: 'booking062',
    studentId: 'currentUser',
    tutorId: 'user001',
    subject: 'Programming Fundamentals',
    date: '2025-07-05',
    timeSlot: '14:00 - 16:00',
    duration: 2,
    location: 'Student Hub @ TP',
    notes: 'Binary trees and tree traversal',
    status: 'completed',
    createdAt: '2025-07-02T10:00:00Z',
    completedAt: '2025-07-05T16:00:00Z',
    hasReview: true
  },
  {
    bookingId: 'booking063',
    studentId: 'currentUser',
    tutorId: 'user002',
    subject: 'Data Analytics',
    date: '2025-07-02',
    timeSlot: '10:00 - 12:00',
    duration: 2,
    location: 'Online (Zoom)',
    notes: 'Regression analysis and prediction',
    status: 'completed',
    createdAt: '2025-06-29T09:00:00Z',
    completedAt: '2025-07-02T12:00:00Z',
    hasReview: true
  },
  {
    bookingId: 'booking064',
    studentId: 'currentUser',
    tutorId: 'user006',
    subject: 'Database Design & Administration',
    date: '2025-06-28',
    timeSlot: '15:00 - 17:00',
    duration: 2,
    location: 'Library @ TP',
    notes: 'Database security and encryption',
    status: 'completed',
    createdAt: '2025-06-25T10:00:00Z',
    completedAt: '2025-06-28T17:00:00Z',
    hasReview: true
  },
  {
    bookingId: 'booking065',
    studentId: 'currentUser',
    tutorId: 'user001',
    subject: 'Object-Oriented Programming',
    date: '2025-06-25',
    timeSlot: '14:00 - 16:00',
    duration: 2,
    location: 'Library @ TP',
    notes: 'Strategy and Template Method patterns',
    status: 'completed',
    createdAt: '2025-06-22T10:00:00Z',
    completedAt: '2025-06-25T16:00:00Z',
    hasReview: true
  },
  {
    bookingId: 'booking066',
    studentId: 'currentUser',
    tutorId: 'user002',
    subject: 'Python Programming',
    date: '2025-06-21',
    timeSlot: '10:00 - 12:00',
    duration: 2,
    location: 'Online (Zoom)',
    notes: 'Asyncio and concurrent programming',
    status: 'completed',
    createdAt: '2025-06-18T09:00:00Z',
    completedAt: '2025-06-21T12:00:00Z',
    hasReview: true
  },
  {
    bookingId: 'booking067',
    studentId: 'currentUser',
    tutorId: 'user006',
    subject: 'Cloud Computing with AWS',
    date: '2025-06-18',
    timeSlot: '15:00 - 17:00',
    duration: 2,
    location: 'Online (Zoom)',
    notes: 'ECS and container orchestration',
    status: 'completed',
    createdAt: '2025-06-15T10:00:00Z',
    completedAt: '2025-06-18T17:00:00Z',
    hasReview: false
  },
  {
    bookingId: 'booking068',
    studentId: 'currentUser',
    tutorId: 'user001',
    subject: 'Web Application Development',
    date: '2025-06-14',
    timeSlot: '14:00 - 16:00',
    duration: 2,
    location: 'Library @ TP',
    notes: 'Server-side rendering with Next.js',
    status: 'completed',
    createdAt: '2025-06-11T10:00:00Z',
    completedAt: '2025-06-14T16:00:00Z',
    hasReview: true
  },
  {
    bookingId: 'booking069',
    studentId: 'currentUser',
    tutorId: 'user002',
    subject: 'Machine Learning Fundamentals',
    date: '2025-06-11',
    timeSlot: '10:00 - 12:00',
    duration: 2,
    location: 'Student Hub @ TP',
    notes: 'Hyperparameter tuning',
    status: 'completed',
    createdAt: '2025-06-08T09:00:00Z',
    completedAt: '2025-06-11T12:00:00Z',
    hasReview: true
  },
  {
    bookingId: 'booking070',
    studentId: 'currentUser',
    tutorId: 'user006',
    subject: 'Database Design & Administration',
    date: '2025-06-07',
    timeSlot: '15:00 - 17:00',
    duration: 2,
    location: 'Library @ TP',
    notes: 'Data warehousing concepts',
    status: 'completed',
    createdAt: '2025-06-04T10:00:00Z',
    completedAt: '2025-06-07T17:00:00Z',
    hasReview: true
  },
  {
    bookingId: 'booking071',
    studentId: 'currentUser',
    tutorId: 'user001',
    subject: 'Programming Fundamentals',
    date: '2025-06-04',
    timeSlot: '14:00 - 16:00',
    duration: 2,
    location: 'Student Hub @ TP',
    notes: 'Sorting algorithms comparison',
    status: 'completed',
    createdAt: '2025-06-01T10:00:00Z',
    completedAt: '2025-06-04T16:00:00Z',
    hasReview: true
  },
  {
    bookingId: 'booking072',
    studentId: 'currentUser',
    tutorId: 'user002',
    subject: 'Data Analytics',
    date: '2025-05-31',
    timeSlot: '10:00 - 12:00',
    duration: 2,
    location: 'Online (Zoom)',
    notes: 'Clustering and segmentation',
    status: 'completed',
    createdAt: '2025-05-28T09:00:00Z',
    completedAt: '2025-05-31T12:00:00Z',
    hasReview: true
  },
  {
    bookingId: 'booking073',
    studentId: 'currentUser',
    tutorId: 'user006',
    subject: 'Web Application Development',
    date: '2025-05-28',
    timeSlot: '16:00 - 18:00',
    duration: 2,
    location: 'Library @ TP',
    notes: 'Responsive design and CSS Grid',
    status: 'completed',
    createdAt: '2025-05-25T10:00:00Z',
    completedAt: '2025-05-28T18:00:00Z',
    hasReview: true
  },
  {
    bookingId: 'booking074',
    studentId: 'currentUser',
    tutorId: 'user001',
    subject: 'Object-Oriented Programming',
    date: '2025-05-24',
    timeSlot: '14:00 - 16:00',
    duration: 2,
    location: 'Library @ TP',
    notes: 'Adapter and Facade patterns',
    status: 'completed',
    createdAt: '2025-05-21T10:00:00Z',
    completedAt: '2025-05-24T16:00:00Z',
    hasReview: true
  },
  {
    bookingId: 'booking075',
    studentId: 'currentUser',
    tutorId: 'user002',
    subject: 'Python Programming',
    date: '2025-05-21',
    timeSlot: '10:00 - 12:00',
    duration: 2,
    location: 'Online (Zoom)',
    notes: 'Type hints and mypy',
    status: 'completed',
    createdAt: '2025-05-18T09:00:00Z',
    completedAt: '2025-05-21T12:00:00Z',
    hasReview: true
  },
  {
    bookingId: 'booking076',
    studentId: 'currentUser',
    tutorId: 'user006',
    subject: 'Cloud Computing with AWS',
    date: '2025-05-17',
    timeSlot: '15:00 - 17:00',
    duration: 2,
    location: 'Online (Zoom)',
    notes: 'CloudFormation and infrastructure as code',
    status: 'completed',
    createdAt: '2025-05-14T10:00:00Z',
    completedAt: '2025-05-17T17:00:00Z',
    hasReview: false
  },
  {
    bookingId: 'booking077',
    studentId: 'currentUser',
    tutorId: 'user001',
    subject: 'Database Design & Administration',
    date: '2025-05-14',
    timeSlot: '14:00 - 16:00',
    duration: 2,
    location: 'Library @ TP',
    notes: 'OLAP vs OLTP systems',
    status: 'completed',
    createdAt: '2025-05-11T10:00:00Z',
    completedAt: '2025-05-14T16:00:00Z',
    hasReview: true
  },
  {
    bookingId: 'booking078',
    studentId: 'currentUser',
    tutorId: 'user002',
    subject: 'Machine Learning Fundamentals',
    date: '2025-05-10',
    timeSlot: '10:00 - 12:00',
    duration: 2,
    location: 'Student Hub @ TP',
    notes: 'Cross-validation techniques',
    status: 'completed',
    createdAt: '2025-05-07T09:00:00Z',
    completedAt: '2025-05-10T12:00:00Z',
    hasReview: true
  },
  {
    bookingId: 'booking079',
    studentId: 'currentUser',
    tutorId: 'user006',
    subject: 'Web Application Development',
    date: '2025-05-07',
    timeSlot: '16:00 - 18:00',
    duration: 2,
    location: 'Library @ TP',
    notes: 'Performance optimization and lazy loading',
    status: 'completed',
    createdAt: '2025-05-04T10:00:00Z',
    completedAt: '2025-05-07T18:00:00Z',
    hasReview: true
  },
  {
    bookingId: 'booking080',
    studentId: 'currentUser',
    tutorId: 'user001',
    subject: 'Programming Fundamentals',
    date: '2025-05-03',
    timeSlot: '14:00 - 16:00',
    duration: 2,
    location: 'Student Hub @ TP',
    notes: 'Hash tables and collision handling',
    status: 'completed',
    createdAt: '2025-04-30T10:00:00Z',
    completedAt: '2025-05-03T16:00:00Z',
    hasReview: true
  },
  // Additional bookings on same dates to create darker colors in activity calendar
  {
    bookingId: 'booking081',
    studentId: 'currentUser',
    tutorId: 'user002',
    subject: 'Python Programming',
    date: '2025-10-28',
    timeSlot: '10:00 - 12:00',
    duration: 2,
    location: 'Online (Zoom)',
    notes: 'Advanced Python concepts',
    status: 'completed',
    createdAt: '2025-10-25T09:00:00Z',
    completedAt: '2025-10-28T12:00:00Z',
    hasReview: true
  },
  {
    bookingId: 'booking082',
    studentId: 'currentUser',
    tutorId: 'user006',
    subject: 'Database Design & Administration',
    date: '2025-10-28',
    timeSlot: '18:00 - 20:00',
    duration: 2,
    location: 'Library @ TP',
    notes: 'Database optimization',
    status: 'completed',
    createdAt: '2025-10-25T10:00:00Z',
    completedAt: '2025-10-28T20:00:00Z',
    hasReview: true
  },
  {
    bookingId: 'booking083',
    studentId: 'currentUser',
    tutorId: 'user001',
    subject: 'Web Application Development',
    date: '2025-10-26',
    timeSlot: '14:00 - 16:00',
    duration: 2,
    location: 'Library @ TP',
    notes: 'React advanced patterns',
    status: 'completed',
    createdAt: '2025-10-23T10:00:00Z',
    completedAt: '2025-10-26T16:00:00Z',
    hasReview: true
  },
  {
    bookingId: 'booking084',
    studentId: 'currentUser',
    tutorId: 'user002',
    subject: 'Machine Learning Fundamentals',
    date: '2025-10-24',
    timeSlot: '10:00 - 12:00',
    duration: 2,
    location: 'Online (Zoom)',
    notes: 'Deep learning introduction',
    status: 'completed',
    createdAt: '2025-10-21T09:00:00Z',
    completedAt: '2025-10-24T12:00:00Z',
    hasReview: true
  },
  {
    bookingId: 'booking085',
    studentId: 'currentUser',
    tutorId: 'user006',
    subject: 'Cloud Computing with AWS',
    date: '2025-10-22',
    timeSlot: '16:00 - 18:00',
    duration: 2,
    location: 'Online (Zoom)',
    notes: 'Kubernetes basics',
    status: 'completed',
    createdAt: '2025-10-19T10:00:00Z',
    completedAt: '2025-10-22T18:00:00Z',
    hasReview: false
  },
  {
    bookingId: 'booking086',
    studentId: 'currentUser',
    tutorId: 'user001',
    subject: 'Programming Fundamentals',
    date: '2025-10-20',
    timeSlot: '10:00 - 12:00',
    duration: 2,
    location: 'Student Hub @ TP',
    notes: 'Advanced algorithms',
    status: 'completed',
    createdAt: '2025-10-17T10:00:00Z',
    completedAt: '2025-10-20T12:00:00Z',
    hasReview: true
  },
  {
    bookingId: 'booking087',
    studentId: 'currentUser',
    tutorId: 'user002',
    subject: 'Data Analytics',
    date: '2025-10-19',
    timeSlot: '14:00 - 16:00',
    duration: 2,
    location: 'Library @ TP',
    notes: 'Big data processing',
    status: 'completed',
    createdAt: '2025-10-16T10:00:00Z',
    completedAt: '2025-10-19T16:00:00Z',
    hasReview: true
  },
  {
    bookingId: 'booking088',
    studentId: 'currentUser',
    tutorId: 'user006',
    subject: 'Web Application Development',
    date: '2025-10-17',
    timeSlot: '16:00 - 18:00',
    duration: 2,
    location: 'Online (Zoom)',
    notes: 'TypeScript advanced types',
    status: 'completed',
    createdAt: '2025-10-14T10:00:00Z',
    completedAt: '2025-10-17T18:00:00Z',
    hasReview: true
  },
  {
    bookingId: 'booking089',
    studentId: 'currentUser',
    tutorId: 'user001',
    subject: 'Object-Oriented Programming',
    date: '2025-10-15',
    timeSlot: '10:00 - 12:00',
    duration: 2,
    location: 'Library @ TP',
    notes: 'Microservices patterns',
    status: 'completed',
    createdAt: '2025-10-12T10:00:00Z',
    completedAt: '2025-10-15T12:00:00Z',
    hasReview: true
  },
  {
    bookingId: 'booking090',
    studentId: 'currentUser',
    tutorId: 'user002',
    subject: 'Python Programming',
    date: '2025-10-14',
    timeSlot: '14:00 - 16:00',
    duration: 2,
    location: 'Online (Zoom)',
    notes: 'Python performance optimization',
    status: 'completed',
    createdAt: '2025-10-11T09:00:00Z',
    completedAt: '2025-10-14T16:00:00Z',
    hasReview: true
  },
  {
    bookingId: 'booking091',
    studentId: 'currentUser',
    tutorId: 'user006',
    subject: 'Database Design & Administration',
    date: '2025-10-11',
    timeSlot: '16:00 - 18:00',
    duration: 2,
    location: 'Library @ TP',
    notes: 'NoSQL database design',
    status: 'completed',
    createdAt: '2025-10-08T10:00:00Z',
    completedAt: '2025-10-11T18:00:00Z',
    hasReview: true
  },
  {
    bookingId: 'booking092',
    studentId: 'currentUser',
    tutorId: 'user001',
    subject: 'Web Application Development',
    date: '2025-10-09',
    timeSlot: '10:00 - 12:00',
    duration: 2,
    location: 'Student Hub @ TP',
    notes: 'GraphQL subscriptions',
    status: 'completed',
    createdAt: '2025-10-06T10:00:00Z',
    completedAt: '2025-10-09T12:00:00Z',
    hasReview: true
  },
  {
    bookingId: 'booking093',
    studentId: 'currentUser',
    tutorId: 'user002',
    subject: 'Machine Learning Fundamentals',
    date: '2025-10-08',
    timeSlot: '14:00 - 16:00',
    duration: 2,
    location: 'Online (Zoom)',
    notes: 'Computer vision basics',
    status: 'completed',
    createdAt: '2025-10-05T09:00:00Z',
    completedAt: '2025-10-08T16:00:00Z',
    hasReview: true
  },
  {
    bookingId: 'booking094',
    studentId: 'currentUser',
    tutorId: 'user006',
    subject: 'Cloud Computing with AWS',
    date: '2025-10-05',
    timeSlot: '10:00 - 12:00',
    duration: 2,
    location: 'Online (Zoom)',
    notes: 'AWS security best practices',
    status: 'completed',
    createdAt: '2025-10-02T10:00:00Z',
    completedAt: '2025-10-05T12:00:00Z',
    hasReview: false
  },
  {
    bookingId: 'booking095',
    studentId: 'currentUser',
    tutorId: 'user001',
    subject: 'Programming Fundamentals',
    date: '2025-10-03',
    timeSlot: '16:00 - 18:00',
    duration: 2,
    location: 'Library @ TP',
    notes: 'System design fundamentals',
    status: 'completed',
    createdAt: '2025-09-30T10:00:00Z',
    completedAt: '2025-10-03T18:00:00Z',
    hasReview: true
  },
  {
    bookingId: 'booking096',
    studentId: 'currentUser',
    tutorId: 'user002',
    subject: 'Data Analytics',
    date: '2025-10-01',
    timeSlot: '14:00 - 16:00',
    duration: 2,
    location: 'Library @ TP',
    notes: 'Data pipeline architecture',
    status: 'completed',
    createdAt: '2025-09-28T10:00:00Z',
    completedAt: '2025-10-01T16:00:00Z',
    hasReview: true
  },
  {
    bookingId: 'booking097',
    studentId: 'currentUser',
    tutorId: 'user006',
    subject: 'Web Application Development',
    date: '2025-09-30',
    timeSlot: '10:00 - 12:00',
    duration: 2,
    location: 'Online (Zoom)',
    notes: 'React performance optimization',
    status: 'completed',
    createdAt: '2025-09-27T10:00:00Z',
    completedAt: '2025-09-30T12:00:00Z',
    hasReview: true
  },
  {
    bookingId: 'booking098',
    studentId: 'currentUser',
    tutorId: 'user001',
    subject: 'Object-Oriented Programming',
    date: '2025-09-27',
    timeSlot: '16:00 - 18:00',
    duration: 2,
    location: 'Library @ TP',
    notes: 'CQRS pattern',
    status: 'completed',
    createdAt: '2025-09-24T10:00:00Z',
    completedAt: '2025-09-27T18:00:00Z',
    hasReview: true
  },
  {
    bookingId: 'booking099',
    studentId: 'currentUser',
    tutorId: 'user002',
    subject: 'Python Programming',
    date: '2025-09-24',
    timeSlot: '14:00 - 16:00',
    duration: 2,
    location: 'Online (Zoom)',
    notes: 'Python metaclasses',
    status: 'completed',
    createdAt: '2025-09-21T09:00:00Z',
    completedAt: '2025-09-24T16:00:00Z',
    hasReview: true
  },
  {
    bookingId: 'booking100',
    studentId: 'currentUser',
    tutorId: 'user006',
    subject: 'Database Design & Administration',
    date: '2025-09-21',
    timeSlot: '10:00 - 12:00',
    duration: 2,
    location: 'Library @ TP',
    notes: 'Database migration strategies',
    status: 'completed',
    createdAt: '2025-09-18T10:00:00Z',
    completedAt: '2025-09-21T12:00:00Z',
    hasReview: true
  },
  {
    bookingId: 'booking101',
    studentId: 'currentUser',
    tutorId: 'user001',
    subject: 'Web Application Development',
    date: '2025-09-19',
    timeSlot: '16:00 - 18:00',
    duration: 2,
    location: 'Online (Zoom)',
    notes: 'Server-side caching',
    status: 'completed',
    createdAt: '2025-09-16T10:00:00Z',
    completedAt: '2025-09-19T18:00:00Z',
    hasReview: true
  },
  {
    bookingId: 'booking102',
    studentId: 'currentUser',
    tutorId: 'user002',
    subject: 'Machine Learning Fundamentals',
    date: '2025-09-16',
    timeSlot: '10:00 - 12:00',
    duration: 2,
    location: 'Student Hub @ TP',
    notes: 'Transfer learning',
    status: 'completed',
    createdAt: '2025-09-13T09:00:00Z',
    completedAt: '2025-09-16T12:00:00Z',
    hasReview: true
  },
  {
    bookingId: 'booking103',
    studentId: 'currentUser',
    tutorId: 'user006',
    subject: 'Cloud Computing with AWS',
    date: '2025-09-13',
    timeSlot: '16:00 - 18:00',
    duration: 2,
    location: 'Online (Zoom)',
    notes: 'AWS cost optimization',
    status: 'completed',
    createdAt: '2025-09-10T10:00:00Z',
    completedAt: '2025-09-13T18:00:00Z',
    hasReview: false
  },
  {
    bookingId: 'booking104',
    studentId: 'currentUser',
    tutorId: 'user001',
    subject: 'Programming Fundamentals',
    date: '2025-09-10',
    timeSlot: '10:00 - 12:00',
    duration: 2,
    location: 'Library @ TP',
    notes: 'Concurrency patterns',
    status: 'completed',
    createdAt: '2025-09-07T10:00:00Z',
    completedAt: '2025-09-10T12:00:00Z',
    hasReview: true
  },
  {
    bookingId: 'booking105',
    studentId: 'currentUser',
    tutorId: 'user002',
    subject: 'Data Analytics',
    date: '2025-09-06',
    timeSlot: '14:00 - 16:00',
    duration: 2,
    location: 'Online (Zoom)',
    notes: 'Real-time analytics',
    status: 'completed',
    createdAt: '2025-09-03T10:00:00Z',
    completedAt: '2025-09-06T16:00:00Z',
    hasReview: true
  },
  {
    bookingId: 'booking106',
    studentId: 'currentUser',
    tutorId: 'user006',
    subject: 'Web Application Development',
    date: '2025-09-03',
    timeSlot: '16:00 - 18:00',
    duration: 2,
    location: 'Library @ TP',
    notes: 'Micro-frontends architecture',
    status: 'completed',
    createdAt: '2025-08-31T10:00:00Z',
    completedAt: '2025-09-03T18:00:00Z',
    hasReview: true
  },
  {
    bookingId: 'booking107',
    studentId: 'currentUser',
    tutorId: 'user001',
    subject: 'Object-Oriented Programming',
    date: '2025-08-30',
    timeSlot: '10:00 - 12:00',
    duration: 2,
    location: 'Library @ TP',
    notes: 'Domain-driven design',
    status: 'completed',
    createdAt: '2025-08-27T10:00:00Z',
    completedAt: '2025-08-30T12:00:00Z',
    hasReview: true
  },
  {
    bookingId: 'booking108',
    studentId: 'currentUser',
    tutorId: 'user002',
    subject: 'Python Programming',
    date: '2025-08-27',
    timeSlot: '16:00 - 18:00',
    duration: 2,
    location: 'Online (Zoom)',
    notes: 'Python packaging and distribution',
    status: 'completed',
    createdAt: '2025-08-24T09:00:00Z',
    completedAt: '2025-08-27T18:00:00Z',
    hasReview: true
  },
  {
    bookingId: 'booking109',
    studentId: 'currentUser',
    tutorId: 'user006',
    subject: 'Database Design & Administration',
    date: '2025-08-23',
    timeSlot: '10:00 - 12:00',
    duration: 2,
    location: 'Library @ TP',
    notes: 'Time-series databases',
    status: 'completed',
    createdAt: '2025-08-20T10:00:00Z',
    completedAt: '2025-08-23T12:00:00Z',
    hasReview: true
  },
  {
    bookingId: 'booking110',
    studentId: 'currentUser',
    tutorId: 'user001',
    subject: 'Web Application Development',
    date: '2025-08-20',
    timeSlot: '16:00 - 18:00',
    duration: 2,
    location: 'Online (Zoom)',
    notes: 'WebAssembly introduction',
    status: 'completed',
    createdAt: '2025-08-17T10:00:00Z',
    completedAt: '2025-08-20T18:00:00Z',
    hasReview: true
  }
];

// Mock Credit Transaction Data
export const mockCreditTransactions = [
  {
    transactionId: 'trans001',
    userId: 'currentUser',
    amount: 100,
    type: 'initial_bonus',
    balance: 100,
    description: 'Welcome bonus - Thanks for joining Tu2tor!',
    createdAt: '2024-09-15T08:30:00Z'
  },
  {
    transactionId: 'trans002',
    userId: 'currentUser',
    amount: -10,
    type: 'booking_cost',
    relatedId: 'booking001',
    balance: 90,
    description: 'Booked session with John Tan - OOP',
    createdAt: '2024-10-20T10:00:00Z'
  },
  {
    transactionId: 'trans003',
    userId: 'currentUser',
    amount: 20,
    type: 'booking_reward',
    relatedId: 'booking003',
    balance: 110,
    description: 'Completed tutoring session - Database Design',
    createdAt: '2024-10-15T17:00:00Z'
  },
  {
    transactionId: 'trans004',
    userId: 'currentUser',
    amount: 5,
    type: 'review_bonus',
    relatedId: 'review001',
    balance: 115,
    description: '5-star review bonus - Keep it up!',
    createdAt: '2024-10-15T20:00:00Z'
  }
];

// Current logged-in user
export const currentUser = {
  userId: 'currentUser',
  email: 'alex.student@student.tp.edu.sg',
  username: 'Alex Tan Kai Ming',
  studentId: '2301999Z',
  major: 'Information Technology',
  yearOfStudy: 2,
  avatar: 'https://ui-avatars.com/api/?name=Alex+Tan&background=4f46e5&color=fff',
  role: ['student', 'tutor'],
  credits: 115,
  points: 50,
  badges: [BADGE_TYPES.NEWBIE],
  school: 'Temasek Polytechnic',
  createdAt: '2024-04-15T08:30:00Z',
  isActive: true
};
